 
	<?php foreach($activities as $activity){ ?>
	<div class="activity-outer">
		<div class="activity-img">
		<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activity->user_profile_name)) ?>" class="profile-img-link">
		<?php if($activity->profile_photo!='') {  ?>
			<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $activity->user_id ?>/66x66/<?php echo $activity->profile_photo; ?>" alt="" />
		<?php }else if($activity->user_register_type == 'facebook' && $activity->user_fbid!=''){ ?>
			 <img src="https://graph.facebook.com/<?php echo $activity->user_fbid; ?>/picture?width=66&&height=66" />
		<?php }else{ ?>
			<img src="<?php echo $this->basePath() ?>/public/images/noimg.jpg" alt="" />
		<?php } ?>
		</a>
		</div>
		<div class="activity-text">
			<div class="activity-msg"><a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$activity->parent_seo_title, 'planet_id'=>$activity->group_seo_title,'id'=>$activity->group_activity_id)) ?>"><?php echo $activity->group_activity_title; ?></a></div>
			<div class="activity-details">
				<div class="activity-name">by <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activity->user_profile_name)) ?>"><?php echo  $activity->user_given_name; ?></a></div>
				<div class="activity-location"><?php echo  $activity->group_activity_location; ?></div>
				<div class="clear"></div>
				<div class="activity-msg"><?php echo $activity->group_activity_content; ?></div>
				<div class="activity-time"><?php echo $activity->group_activity_start_timestamp;  ?></div>
				<div class="activity-joined"><?php echo $activity->member_count; ?> joined</div>
				<div class="clear"></div>
			</div>
			
		</div>
		<div class="activity-rocket"><img src="<?php echo $this->basePath(); ?>/public/images/rocket-icon.png" alt="" /></div>
		<div class="join-ride-butn">
		<?php if($activity->is_member){ ?>
			<span>On board!</span>
	<?php	}else{ ?>
		<a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$activity->parent_seo_title, 'planet_id'=>$activity->group_seo_title,'id'=>$activity->group_activity_id)) ?>"><img src="<?php echo $this->basePath(); ?>/public/images/join-ride-butn.png" alt="" /></a><?php } ?></div>
		<div class="clear"></div>
	</div>
	<?php } ?>
 