<?php if(isset($error) && count($error)) : ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<div class="all-members-list">
<?php 
if(!empty($members)){
foreach($members as $member){ ?>
	<div class="activity-member profile-image-comn">
		<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$member->user_profile_name)) ?>" class="profile-img-link">
		<?php if($member->profile_photo!=''){ ?>
		<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $member->user_id ?>/66x66/<?php echo $member->profile_photo; ?>" alt="" />
		<?php }else if($member->user_register_type == 'facebook' && $member->user_fbid!=''){ ?>
			<img src="https://graph.facebook.com/<?php echo $member->user_fbid; ?>/picture?width=66&&height=66" />
		<?php }else{ ?>
		<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
		<?php } ?>
		</a>
		<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$member->user_profile_name)) ?>"><?php echo $member->user_given_name; ?></a>
	</div>
	<?php } 
	}else{ echo "No more members in this activity"; }?>
	
	<div class="clear"></div>
</div>