<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8"/>
        <title>Dashboard I Admin Panel</title>

        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/layout-admin.css" type="text/css" media="screen" />

        <!--[if lt IE 9]>
        <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="<?php echo $this->basePath(); ?>/js/jquery-1.5.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/js/hideshow.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.equalHeight.js"></script>
        <script type="text/javascript">
            $(document).ready(function()
            {
                $(".tablesorter").tablesorter();
            }
            );
            $(document).ready(function() {

                //When page loads...
                $(".tab_content").hide(); //Hide all content
                //$("ul.tabs li:first").addClass("active").show(); //Activate first tab
                $(".tab_content:first").show(); //Show first tab content

                //On Click Event
                $("ul.tabs li").click(function() {

                    $("ul.tabs li").removeClass("active"); //Remove any "active" class
                    $(this).addClass("active"); //Add "active" class to selected tab
                    $(".tab_content").hide(); //Hide all tab content

                    var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
                    $(activeTab).fadeIn(); //Fade in the active ID content
                    return false;
                });

            });
        </script>
        <script type="text/javascript">
            $(function() {
                $('.column').equalHeight();
            });
        </script>

    </head>


    <body>
 
        <header id="header">
            <hgroup>
                <h1 class="site_title"><a href="index.html">1625(Jeera) Admin</a></h1>
                <h2 class="section_title">Dashboard</h2><div class="btn_view_site"><a href="<?php echo $this->basePath();?>">View Site</a></div>
            </hgroup>
        </header> <!-- end of header bar -->

       

        <aside id="sidebar" class="column">
            <section id="secondary_bar">
            <div class="user">
                <p>John Doe (<a href="#">3 Messages</a>)</p>
                <!-- <a class="logout_user" href="#" title="Logout">Logout</a> -->
            </div>
                </section>
            <form class="quick_search">
                <input type="text" value="Quick Search" onfocus="if (!this._haschanged) {
                    this.value = ''
                }
                ;
                this._haschanged = true;">
            </form>
            <hr/>
            <h3>Interests(Tags)</h3>
            <ul class="toggle">
                <li class="icn_tags"><a href="<?php echo $this->url('admin/admin-tags') ?>">Manage Interest(Tags)</a></li>
                <li class="icn_tags"><a href="<?php echo $this->url('admin/admin-user-tags') ?>">Manage User Interest(Tags)</a></li>
                <li class="icn_tags"><a href="<?php echo $this->url('admin/admin-planet-tags') ?>">Manage Planet Interest(Tags)</a></li>

            </ul>
            <h3>Users</h3>
            <ul class="toggle">
                <li class="icn_add_user"><a href="#">Add New User</a></li>
                <li class="icn_view_users"><a href="#">View Users</a></li>
                <li class="icn_profile"><a href="#">Your Profile</a></li>
            </ul>
            <h3>Categories</h3>
            <ul class="toggle">
                <li class="icn_folder"><a href="<?php echo $this->url('admin/admin-galaxy') ?>">Manage Galaxy</a></li>
                <li class="icn_photo"><a href="<?php echo $this->url('admin/admin-planet') ?>">Manage Planets</a></li>
                <!--<li class="icn_audio"><a href="#">Audio</a></li>
                <li class="icn_video"><a href="#">Video</a></li>-->
            </ul>
			<h3>Activity</h3>
            <ul class="toggle">
                <li class="icn_folder"><a href="<?php echo $this->url('admin/admin-activity') ?>">Planet Activity</a></li>
                
            </ul>
			<h3>Notification</h3>
            <ul class="toggle">
                <li class="icn_folder"><a href="<?php echo $this->url('admin/admin-notification') ?>">Notification Types</a></li>
                
            </ul>
			<h3>Other</h3>
            <ul class="toggle">
                <li class="icn_world"><a href="<?php echo $this->url('admin/admin-country') ?>">Country List</a></li>
                
            </ul>
            <h3>Admin</h3>
            <ul class="toggle">
                <li class="icn_settings"><a href="#">Options</a></li>
                <li class="icn_jump_back"><a href="#">Logout</a></li>
            </ul>

            <footer>
                <hr />
                <p><strong>Copyright &copy; 2011 Website Admin</strong></p>
                <p>Theme by <a href="<?php echo $this->basePath();?>">Y2M</a></p>
            </footer>
        </aside><!-- end of sidebar -->





<?php echo $this->content; ?>

      


    </body>

</html>