<?php
// module/User/view/user/user/add.phtml:
$this->headTitle($this->translate('Login'));
?>
<!-- <h1><?php //echo $this->escapeHtml($this->translate('Login')); ?></h1> -->
<!--flash Messages.Stored in session-->
<?php if(isset($flashMessages) && count($flashMessages)) : ?>
<ul class="session">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--error Message-->
<?php if(isset($error) && count($error)) : ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--success message-->
<?php if(isset($success) && count($success)) : ?>
<ul class="success">
    <?php foreach ($success as $successmsg) : ?>
    <li><?php echo $successmsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<div class="video-head">Some text here welcoming to Jeera</div>
<div class="video-container">
<video width="806" height="454" controls>
  <source src="<?php echo $this->basePath(); ?>/public/videos/songs.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
 </div>