<?php
// module/User/view/user/user/add.phtml:
$this->headTitle($this->translate('Login'));
?>

<!--flash Messages.Stored in session-->
<?php if(isset($flashMessages) && count($flashMessages)) : ?>
<ul class="session">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?PHP IF(ISSET($form)): ?>
<div class="forgot-container">
	<div class="forgot_logo"><a href="index.html"><img src="<?php echo $this->basePath(); ?>/public/images/jeera-logo-2.png" alt="" /></a></div>
	<div class="forgot_outer">
		<h3>Forgot Password</h3>
		 
		<div class="login-field">
			 	<div class="login-form">
<?php
$form = $this->form;
$url = $this->url()."/$key/$id"; 
$form->setAttribute('action', $url);
//$form->prepare();
?>
<?php echo $this->form()->openTag($form);?>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('csrf'));?>
	</div>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('user_password'));?>
	</div>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('user_retype_password'));?>
	</div>
	<div class="signup-field">
			<?php echo $this->formRow($form->get('submit'));?>			 
		</div>
<?php echo $this->form()->closeTag();?>
	</div>
		</div>
		 
	</div> 
	
</div>
 <?PHP ENDIF; ?>


 
 