 
<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/discussion.js','text/javascript'); ?> 
 
<script>
	var galexy = '<?php echo $planetdetails->galexy_seo_title; ?>';
	var planet = '<?php echo  $planetdetails->group_seo_title; ?>';
</script>
<script type="text/javascript">
$(function() {   
    
	$("#add_discussion").click(function(){
		
		$(".new-activity-container").animate({  height:'toggle' });		
		 
	}); 
	$(document).on("click","#cancel_discussion",function(event){	 
		$(".new-activity-container").animate({  height:'toggle' });				 
	}); 
});
</script>
 
<?php if(empty($error)){  ?>
   <?php echo $this->groupTopWidget; ?> 
  <div class="profile-tabs2">
	<div id="tabs">
		<div class="tabs-outer tabs">
			<ul>  
				<li><a href="<?php echo $this->url('groups/planethome',array('group_id'=>$planetdetails->galexy_seo_title,'planet_id'=>$planetdetails->group_seo_title));?>" class="activity_tab">Activities</a></li>
				<?php if($planetdetails->is_member){ ?> <li class="active"><a href="<?php echo $this->url('groups/group-discussion', array('action' => 'subgroupdetailwithdiscussion', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="discuss_tab">Discussion</a></li>
				<li><a href="<?php echo $this->url('groups/group-media', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="media_tab">Media</a></li> <?php } ?>
				<li><a href="<?php echo $this->url('groups/group-members', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="member_tab">Members</a></li>
			</ul>
            <div class="clear"></div>
         </div>
		 <div id="tabs-1">
			<div class="tab-sub">
				<div class="add-activity-butn"><?php if($planetdetails->is_member&&$discussion_permission){ ?><a href="javascript:void(0);" class="blue-butn" id="add_discussion">Add new Discussion</a><?php }else{ 
				if(isset($group_settings)&&!empty($group_settings)&&$group_settings->group_member_join_type!='NoOne'&&!$is_request&&!$planetdetails->is_member){
				?><a href="javascript:void(0);" class="blue-butn" id="join_group">Join this group</a> <?php } } ?></div>
				<div class="clear"></div>
				<?php if($planetdetails->is_member&&$discussion_permission){ ?>
					<div class="new-activity-container" style="display:none">
						<textarea name="discussion_content" id="discussion_content" placeholder="Name" placeholder="Description"></textarea>
						<div class="add-activity-actions">
							<a href="javascript:void(0)" id="start_discussion" class="blue-butn">Add new</a>
							<a href="javascript:void(0);" class="grey-butn" id="cancel_discussion" style="color:#888888;">Cancel</a>
						</div>
						<div class="clear"></div>
                      </div> 
				<?php } ?>
				<div id="tabs_sub-1"> 
					<div id="activity_list">
						<?php foreach($discussions as $row){ ?>
							<div id="discussion-outer-<?php echo $row['group_discussion_id']; ?>">
							<div class="activity-outer" >
                            	<div class="activity-profileimg profile-image-comn">
								 <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$row['user_profile_name'])) ?>" class="profile-img-link">
								<?php  if($row['profile_photo']!=''){ ?>								 
								<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $row['user_id']; ?>/66x66/<?php echo $row['profile_photo']; ?>" alt="" />
								<?php }else if($row['user_register_type'] == 'facebook' && $row['user_fbid']!=''){ ?>
									<img src="https://graph.facebook.com/<?php echo $row['user_fbid']; ?>/picture?width=66&&height=66" />
								<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
								<?php } ?>
								</a>
								</div>
                                <div class="discussion-main-outer">
                                	<div class="activity-author"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$row['user_profile_name'])) ?>"><?php echo $row['user_given_name']; ?></a></div>
                                    <div class="activity-text" id="discussion_container_<?php echo $row['group_discussion_id']; ?>"><?php echo $row['group_discussion_content']; ?> </div>
									<div ><?php if($discussion_edit_permission||($row['user_id']== $this->layout()->identity->user_id)){ ?><a href="javascript:void(0)" class="edit_discussion" id="editdiscussion_<?php echo $row['group_discussion_id']; ?>">Edit</a>&nbsp;<a href="javascript:void(0)" class="delete_discussion" id="deletediscussion_<?php echo $row['group_discussion_id']; ?>">Delete</a><?php } ?></div>
                                    <div class="activity-details_planet">
                                        <div class="like-comment-outer">
                                            <div class="likes" id="likes_<?php echo $row['group_discussion_id']; ?>">
											<?php if($row['descussion_like']->is_liked){  ?>
												<?php if($planetdetails->is_member){ ?>
													<a href="javascript:void(0)"  class="discussion-unlikes" id="<?php echo $row['group_discussion_id']; ?>"  ><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />  </a>
												<?php }else{  ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /> 
												<?php }
											}else{ ?> 
												<?php if($planetdetails->is_member){ ?>	
													<a href="javascript:void(0)" id="<?php echo $row['group_discussion_id']; ?>" class="discussion-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />  </a>
												<?php }else{ ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
												<?php } ?>
											<?php } ?>
											<?php if($row['descussion_like']->likes_counts){echo $row['descussion_like']->likes_counts;} ?>
											</div>
                                            <div class="likes"><a href="javascript:void(0)"><img src="<?php echo $this->basePath(); ?>/public/images/comments-icon.png" alt="" /></a> <?php if($row['comment_count']){echo $row['comment_count'];} ?> <span><a href="javascript:void(0)">Comment</a></span></div>
                                            <div class="clear"></div>
                                        </div>
                                         
                                         
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                 
                                
                                <div class="clear"></div>
                            </div>
							 <div class="activity-comments">
								<div id="loadmore_<?php echo $row['group_discussion_id']; ?>"><?php if($row['comment_count']>2){ ?><a href="javascript:void(0)" id="<?php echo $row['group_discussion_id']; ?>" class="loadmore_comments">View <span id="comment_count_<?php echo $row['group_discussion_id']; ?>"><?php echo $row['comment_count']-2 ;?></span> more comments</a> <?php } ?></div>
								<div id="comment_area<?php echo $row['group_discussion_id']; ?>">
								<?php  
								$arr_comments = array();
								foreach($row['comments'] as $comments){
									$arr_comments[] = $comments;
								}
								$newcommnt =  array_reverse($arr_comments);
								foreach($newcommnt as $comments){  
								?>
                            	<div class="comments-outer" id="comments-outer-<?php echo $comments->comment_id ?>">
                                    <div class="comment-profil-img">
										<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>" class="profile-img-link">
											<?php if($comments->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $comments->user_id ?>/66x66/<?php echo $comments->profile_photo; ?>" alt="" />
											<?php }else if($comments->user_register_type == 'facebook' && $comments->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $comments->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
										</div>
                                    <div class="comment-text comment-text2" >
                                        <span><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>"><?php echo $comments->user_given_name; ?></a></span>
                                        <div id="comment_text_<?php echo $comments->comment_id; ?>"> <?php echo $comments->comment_content; ?></div>
										
										<div><?php if($comments->user_id == $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="edit_comment_<?php echo $comments->comment_id; ?>" class="edit_comment">Edit</a><?php } ?>
										<?php if($comments->user_id == $this->layout()->identity->user_id || $is_admin ||$row['user_id']== $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="delete_comment_<?php echo $comments->comment_id; ?>" class="delete_comment">Delete</a><?php } ?>
										</div>
										
                                        <div class="activity-comment-like" id="comments_likes<?php echo $comments->comment_id; ?>">
										<?php if($comments->islike){ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-unlikes"><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />
											<?php } ?>
										<?php }else{ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
											<?php } ?>
										<?php }?>
										<?php echo $comments->likes_count; ?>
										</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
								<?php } ?>
								</div>
                                 <?php if($planetdetails->is_member){ ?>
                                <div class="activity-add-comment">
                                	<textarea name="comment" id="comment_<?php echo $row['group_discussion_id']; ?>" class="discussion_comments" placeholder="Comment"></textarea>
                                </div>
								<?php } ?>
                            </div>
						 </div>
						<?php } ?>
						
					</div>
					<div id="activity_loadmore_container" class="btn-loadmore">
						<a href="javascript:void(0)" id="discussion_loadmore" >Load more</a>
					</div>
				</div>
				 
			</div>
		</div>
	</div>
  </div>
 
 <?php }else{ ?>
	<ul>
		<?php foreach($error as $msg){ ?>
			<li><?php echo $msg; ?></li>
		<?php } ?>
	</ul>
 <?php } ?>
 <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 <style>
	#map-canvas, #activity_map{
  height: 400px;

  border: 1px solid #999;
  -moz-box-shadow:    0px 0px 5px #ccc;
  -webkit-box-shadow: 0px 0px 5px #ccc;
  box-shadow:         0px 0px 5px #ccc;
}
 </style>
 <script>
  <?php if($planetdetails->y2m_group_location_lat!=''&&$planetdetails->y2m_group_location_lng!=''){ ?>
		var current_lat = <?php echo $planetdetails->y2m_group_location_lat; ?>;
		var current_lng = <?php echo $planetdetails->y2m_group_location_lng; ?>;
	 <?php }else{  ?>
		var current_lat = 25.271139000000000000;
		var current_lng =55.307485000000040000;
	 <?php } ?>
var geocoder;
var map;
var marker;
var mapselected = 'map1';
// initialise the google maps objects, and add listeners
function gmaps_init(){

  // center of the universe
  var latlng = new google.maps.LatLng(current_lat,current_lng);

  var options = {
    zoom: 7,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP,

  };

  // create our map object
  if(mapselected=='map1')
  map = new google.maps.Map(document.getElementById("map-canvas"), options);
  else
   map = new google.maps.Map(document.getElementById("activity_map"), options);

  // the geocoder object allows us to do latlng lookup based on address
  geocoder = new google.maps.Geocoder();
	 

  // the marker shows us the position of the latest address
  marker = new google.maps.Marker({
    map: map,
	icon: "<?php echo $this->basepath(); ?>/public/images/rocket2-icon.png",
    draggable: true
  });
marker.setPosition(latlng);
  // event triggered when marker is dragged and dropped
  google.maps.event.addListener(marker, 'dragend', function() {
    geocode_lookup( 'latLng', marker.getPosition() );
  });

  // event triggered when map is clicked
  google.maps.event.addListener(map, 'click', function(event) {
    marker.setPosition(event.latLng)
    geocode_lookup( 'latLng', event.latLng  );
  });

  $('#gmaps-error').hide();
}

// move the marker to a new position, and center the map on it
function update_map( geometry ) {
  map.fitBounds( geometry.viewport )
  marker.setPosition( geometry.location )
}

// fill in the UI elements with new position data
function update_ui( address, latLng ) {
if(mapselected=='map1'){
  $('#location').autocomplete("close");
  $('#location').val(address);
  }else{
   $('#address').autocomplete("close");
  $('#address').val(address);
  }
  geo_latitude = latLng.lat(); 
  geo_longitude = latLng.lng(); 
  //$('#gmaps-output-latitude').html(latLng.lat());
  //$('#gmaps-output-longitude').html(latLng.lng());
}

// Query the Google geocode object
//
// type: 'address' for search by address
//       'latLng'  for search by latLng (reverse lookup)
//
// value: search query
//
// update: should we update the map (center map and position marker)?
function geocode_lookup( type, value, update ) {
  // default value: update = false
  update = typeof update !== 'undefined' ? update : false;

  request = {};
  request[type] = value;

  geocoder.geocode(request, function(results, status) {
    $('#gmaps-error').html('');
    $('#gmaps-error').hide();
    if (status == google.maps.GeocoderStatus.OK) {
      // Google geocoding has succeeded!
      if (results[0]) {
        // Always update the UI elements with new location data
        update_ui( results[0].formatted_address,
                   results[0].geometry.location )

        // Only update the map (position marker and center map) if requested
        if( update ) { update_map( results[0].geometry ) }
      } else {
        // Geocoder status ok but no results!?
        $('#gmaps-error').html("Sorry, something went wrong. Try again!");
        $('#gmaps-error').show();
      }
    } else {
      // Google Geocoding has failed. Two common reasons:
      //   * Address not recognised (e.g. search for 'zxxzcxczxcx')
      //   * Location doesn't map to address (e.g. click in middle of Atlantic)

      if( type == 'address' ) {
        // User has typed in an address which we can't geocode to a location
        $('#gmaps-error').html("Sorry! We couldn't find " + value + ". Try a different search term, or click the map." );
        $('#gmaps-error').show();
      } else {
        // User has clicked or dragged marker to somewhere that Google can't do a reverse lookup for
        // In this case we display a warning, clear the address box, but fill in LatLng
        $('#gmaps-error').html("Woah... that's pretty remote! You're going to have to manually enter a place name." );
        $('#gmaps-error').show();
        update_ui('', value)
      }
    };
  });
};

// initialise the jqueryUI autocomplete element
function autocomplete_init() {
	if(mapselected=='map1'){
  $("#location").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }else{
	  $("#address").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }
if(mapselected=='map1'){
  // triggered when user presses a key in the address box
  $("#location").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#location').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#location').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#location').autocomplete("enable")
    }
  });
  }
  else{
	$("#address").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#address').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#address').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#address').autocomplete("enable")
    }
  });
  }
}; // autocomplete_init
		
</script>