<style>
    input[type="text"]
    {
        width:400px
    }
</style>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('notifications/pushnotifyregisteredusers'));
//$form->prepare();
?><?php echo $this->form()->openTag($form);?>
	<div><?php echo $this->formRow($form->get('message')); ?></div>
	<div class="clear"></div>
	<div><?php echo $this->formRow($form->get('submit')); ?></div>
<?php
echo $this->form()->closeTag();
?>