<?php 
$title = 'Tag Categories';
$this->headTitle($title); 
?>
<section id="secondary_bar">
    <div class="breadcrumbs_container">
        <article class="breadcrumbs"><a href="<?php echo $this->url('jadmin') ?>">Admin Dashboard </a><div class="breadcrumb_divider"></div>  <a class="current" href="<?php echo $this->url('jadmin/admin-tags-category') ?>">Manage Tag Categories</a></article>
    </div>
</section>
<section id="main" class="column">
    <article class="module width_3_quarter">
        <header><h3 class="tabs_involved"><?php echo $this->escapeHtml($title); ?></h3>
            <ul class="tabs">
				<li><a href="<?php echo $this->url('jadmin/admin-tag-categories-add');?>">Add New Tag Category</a></li>
            </ul>
        </header>
		<div class="tag_quick_search">
			<form  method="post" action="<?php echo $this->url('jadmin/admin-tags-category');?>">
				<input type="text" id="tag_category_search" name="tag_category_search" value="<?php echo $search; ?>" />
				<input type="submit" value="Search" />
			</form>
		</div>
		<div>Page <?php echo $page  ?> out of <?php echo $total_pages; ?> page</div>
        <div class="tab_container">
            <div id="tab1" class="tab_content">
                <table class="tablesorter" cellspacing="0"> 
                    <thead> 
                        <tr>                          
                            <th>Id </th>
							<th>							
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=> $page,'sort'=>'title','order'=>($field=='title'&&$order=='ASC')?'desc':'asc','search'=>$search));?>">						
							Tag Category Name</a></th>
							<th>Actions</th>
                        </tr> 
                    </thead> 
                    <tbody> 
                        <?php 
						 $i=($page==1)?0:$page-1;
						$i = $i*20;
						foreach($allTagCategoriesData as $tag) : 
						$i++;	?>
                            <tr>                                
                                <td><?php echo $i;?></td>
								<td><?php echo $this->escapeHtml($tag->tag_category_title);?>
								
								<?php if($tag->tag_count){ ?>
								<a href="<?php echo $this->url('jadmin/admin-tags',    array('category'=> $tag->tag_category_id));?>">
								(<?php echo $tag->tag_count; ?> tags)
								<?php } ?>
								</a></td>
                                <td><a href="<?php echo $this->url('jadmin/admin-tag-categories-edit',    array('action'=>'edit', 'id' => $tag->tag_category_id));?>"><img src="<?php echo $this->basePath(); ?>/public/images/edit.png" title="Edit"></a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('jadmin/admin-tag-categories-delete',    array('action'=>'delete', 'id' => $tag->tag_category_id));?>"><img src="<?php echo $this->basePath(); ?>/public/images/trash.png" title="Trash"></a></td> 
                            </tr> 
                        <?php endforeach; ?> 
                    </tbody> 
					<tr>
						<td colspan="3">
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Next &raquo;</a>
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order)));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>1,'sort'=>$field,'order'=>strtolower($order)));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-tags-category',    array('page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Next &raquo;</a>
							<?php } ?>
						</td>
					</tr>
                </table>
            </div>
        </div>
    </article>
    <div class="clear"></div>
    <div class="spacer"></div>
</section>