 <html>
	 <div id="container">
		<?php
		$inc = 0;
		if(isset($LikesUsersListData) && count($LikesUsersListData)) : 
			foreach($LikesUsersListData as $usersdata) {
				if ($inc % 2 == 0 ) {
				echo "<br />";
				}
				echo "<img src=".$usersdata->photo_location.$usersdata->photo_name." width='100' height='100' />&nbsp;&nbsp;".$usersdata->user_given_name."<br />";
				$inc++;
			}
		endif;
		?>
	</div>
</html>
