<section id="secondary_bar">            
	<div class="breadcrumbs_container">
	<article class="breadcrumbs"><a href="<?php echo $this->basePath();?>/jadmin">1625 Admin</a> <div class="breadcrumb_divider"></div> <a class="current">Dashboard</a></article>
	</div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
	<h4 class="alert_info">Welcome to 1625(Jeera) admin panel .</h4>	
	<article class="module width_full">
		<div class="module_content">
			<div class="clear"></div>
		</div>
	</article><!-- end of stats article -->
	<div class="spacer"></div>
</section>