<?php if(isset($flashMessages) && count($flashMessages)) : ?>
<ul class="session">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--error Message-->
<?php if(isset($error) && count($error)) : ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--success message-->
<?php if(isset($success) && count($success)) : ?>
<ul class="success">
    <?php foreach ($success as $successmsg) : ?>
    <li><?php echo $successmsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('jadmin/login'));
//$form->prepare();
?><?php echo $this->form()->openTag($form);?>
	<div><?php echo $this->formRow($form->get('admin_username')); ?></div>
	<div class="clear"></div>
	<div><?php echo $this->formRow($form->get('admin_password')); ?></div>
	<div class="clear"></div>
	<div><?php echo $this->formRow($form->get('submit')); ?></div>
<?php
echo $this->form()->closeTag();
?>