<?php 
if(!empty($error)){
?>
<ul>
<?php foreach($error as $list){ ?>
<li><?php echo $list; ?></li>
<?php } ?>
</ul>
<?php 
}
 ?> 
 <div id="group_members" style="display:none">
	<?php foreach($members as $rows){ ?>	 
		<a href="javascript:void(0)" id="<?php echo $rows->user_id; ?>" class="invite_to_activity">
		<div class="members_area">
			<div class="selected_members-img">
				<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$rows->user_profile_name)) ?>" class="profile-img-link">
			<?php if($rows->profile_photo!=''){ ?>
			<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $rows->user_id ?>/66x66/<?php echo $rows->profile_photo; ?>" alt="" />
			<?php }else if($rows->user_register_type == 'facebook' && $rows->user_fbid!=''){ ?>
				<img src="https://graph.facebook.com/<?php echo $rows->user_fbid; ?>/picture?width=66&&height=66" />
			<?php }else{ ?>
			<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
			<?php } ?>
			</a>
				 
			
			</div>			
			<div class="selected_members-name"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$rows->user_profile_name)) ?>" class="profile-img-link"><?php echo $rows->user_given_name ; ?></a></div>
			<div class="clear"></div>
		</div>
		</a>	
	 	
	<?php } ?>
</div>
 