
	<?php foreach($galexies as $group) { ?> 
	<div class="galaxy-outer">
		<div class="galaxy-img">
		<?php if($group->group_photo_photo!=''){ ?>
			<img src="<?php echo $this->basePath() ?>/public/datagd/galexy/<?php echo $group->group_photo_photo; ?>" alt="" />
		<?php }else{ ?>
			<img src="<?php echo $this->basePath() ?>/public/images/galaxy-noimg.jpg" alt="" />
		<?php } ?>
		</div>
		<div class="galaxy-details">
			<div class="galaxt-icon"></div>
			<div class="galaxy-head">
				<h3><?php  echo $group->group_title; ?></h3>
				<div class="members-amnt"><?php  echo $group->member_count; ?>engaged</div>
			</div>
			<div class="galaxy-butn">
				<a href="<?php echo $this->url('groups/planet',array('group_id'=>$group->group_seo_title));?>">See planets</a>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<?php } ?>
	
	 