<style>
    #fixed {
    height: 500px;
}
</style>
<div id="member_container" ng-app="groupMemberApp" ng-controller="memberController" >
    <div class="feed-filter_outer sub_top-margin">
    	<div class="home-container">
        	<h1><a href="<?php echo $this->basePath(); ?>/groups/{{group_details.group_seo_title}}"><i class="back-button"></i>{{group_details.group_title}}</a></h1>
        </div>
    </div>
    <div class="home-container feeds-container">
    	<div class="filter_sub-outer">
        	<div class="row">
            	<div class="col-lg-7 col-md-6 col-sm-6 col-xs-12">
                	<div class="feed-refresh"><a href="javascript:void(0);" ng-click="showMembers()"><img src="<?php echo $this->basePath(); ?>/public/images/refresh-icon.png" alt="" /></a></div>
                    <div class="show-sorting">
                    	Show: 
                        <span><a href="javascript:void(0);" ng-class="{active : selectedTab === 'All'}" ng-click="showAllMembers()">All</a></span>
                        <span><a href="javascript:void(0);" ng-class="{active : selectedTab === 'Owners'}" ng-click="showOwners()">Group Owners ({{ownerCount}})</a></span>
                        <span><a href="javascript:void(0);" ng-class="{active : selectedTab === 'Friends'}" ng-click="showFriendsMembers()">Your Friends ({{friends_count}})</a></span>
						 <span ng-if="is_owner == 1"><a href="javascript:void(0);" ng-class="{active : selectedTab === 'pending'}" ng-click="showPendingRequests()">Pending Requests ({{pending_requests}})</a></span>
                    </div>
                </div>
          
                <div class="clear"></div>
            </div>
        </div>
          
        <div class="friends_list-container" scroller ng-init="showMembers()">
		        <div ng-if="loader==1" class="loading" align="center"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
                  
            	<!-- Friends List Starts Here -->
                <div ng-if="loader==0" class="friends_list-outer border_radius group_member_list" ng-repeat="items in members" >
                	<div class="post_header">
                    	<span class="vertical_align"></span>
                        <div class="header-profile_image">
						<a href="<?php echo $this->basePath(); ?>/{{items.user_profile_name}}"><img alt="" ng-if="items.profile_photo!=null&&items.profile_photo!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{items.user_id}}/{{ items.profile_photo }}">
						<img alt="" ng-if="items.profile_photo==null||items.profile_photo==''" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg"></a>
						<span class="owner-badge" ng-if="items.is_admin"></span>
						<span id="star{{items.user_id}}"></span>
						</div>
                        <div class="post_profile-name">
                        	<a href="<?php echo $this->basePath(); ?>/{{items.user_profile_name}}">{{items.user_given_name}}</a>
                            <span><i class="group-location"></i>{{items.city}}, {{items.country_code}}</span>
                        </div>						
                        <div class="friend-status_butn" id="addfriend{{items.user_id}}" ng-if="items.is_friend ==1&&profile_data.user_id!=items.user_id"><a ng-click="unFriend(items.user_profile_name)" href="javascript:void(0);" class="default_butn_red">Unfriend</a></div>
						<div class="friend-status_butn"  id="addfriend{{items.user_id}}" ng-if="items.is_friend ==0&&items.isPending==1&&profile_data.user_id!=items.user_id"><a ng-click="addFriend(items.user_id)" href="javascript:void(0);" class="default_butn_grey">Pending</a></div>
						<div class="friend-status_butn"  id="addfriend{{items.user_id}}" ng-if="items.is_friend ==0&&items.is_requested==0&&items.isPending==0&&profile_data.user_id!=items.user_id"><a ng-click="addFriend(items.user_profile_name)" href="javascript:void(0);" class="default_butn_blue">Add Friend</a></div>
						<div class="friend-status_butn"  id="addfriend{{items.user_id}}" >
						<a ng-click="acceptFriendRequest(items.user_profile_name)"  href="javascript:void(0);" ng-if="items.is_friend ==0&&items.is_requested==1&&profile_data.user_id!=items.user_id" class="friend_accept">Accept Request</a>
						<a href="javascript:void(0);" ng-if="items.is_friend ==0&&items.is_requested==1&&profile_data.user_id!=items.user_id" class="friend_ignore" ng-click="rejectFriendRequest(items.user_profile_name)" title="Ignore Request"></a>
						</div>	
                        <div class="clear"></div>
                    </div>
                    <div class="friend_interest">
                    	<span>Interested In ({{items.tag_count}})</span>
                    	<div class="friend_interest-icons" >
							<img  alt="" ng-repeat="tagitem in items.tag_category" ng-if="tagitem.tag_category_icon!=''&&$index<=3" src="<?php echo $this->basePath(); ?>/public/{{ image_paths.tag_category }}/{{tagitem.tag_category_icon}}" alt="{{tagitem.tag_category_title}}" />
                            <img ng-repeat="tagitem in items.tag_category" ng-if="tagitem.tag_category_icon==''&&$index<=3" src="<?php echo $this->basePath(); ?>/public/images/category-icon.png" alt="{{tagitem.tag_category_title}}" /> 
							<span class="interest_more" ng-if="item.tag_category_count>4">+{{ items.tag_category_count- 4 }}</span>
                          
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="group_members-friends">
                        <div class="group_members">groups joined: <span>{{items.group_count}}</span></div>
                        <div class="group_friends">groups created: <span>{{items.created_group_count}}</span></div>
                        <div class="clear"></div>
                    </div>
                    <!-- Group member Options starts here -->
                    <div id="member_options" class="group_member-options" ng-if="is_owner==1&&selectedTab != 'pending'"   >
                    	<div class="promote-outer" id="promote{{items.user_id}}" ng-if="items.user_group_is_owner!=1&&items.user_group_role == 0">
                        	<a href="javascript:void(0);" ng-click="promoteadmin(items.user_id)"><i class="promote-admin"></i> promote to admin</a>
                        </div>
						<div class="revoke-outer" ng-if="items.user_group_is_owner!=1&&items.user_group_role == 1">
                        	<a href="javascript:void(0);" ng-click="revokeadmin(items.user_id)"><i class="revoke"></i> revoke rights</a>
                        </div>
                        <div class="remove_from-group" id="removeuser" ng-if="items.user_group_is_owner!=1">
                        	<a href="javascript:void(0);"  ng-click="removeuser(items.user_id)"><i class="remove_group-mem"></i> remove from group</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <!-- Group member Options ends here -->
					       
                    <div class="post_comment-outer" ng-if="selectedTab =='pending'">
						<div  ng-repeat="question in items.questionnaire">
                    	<div class="pending_requ-question">
                        	<span>Q{{$index+1}}</span>{{question.question}}
                        </div>
                        <div class="pending_requ-answer">
                        	<i class="answer-bullet"></i>
							<span ng-if="question.answer_type=='Textarea'">{{question.answer}}</span>
							<span ng-if="question.answer_type!='Textarea'">
								<p ng-repeat="option in question.options">{{option.option}}</p>
							</span>
                        </div>
                     </div>
                        
                        <div class="friend-status_butn">
                        	<a title="Ignore Request" class="friend_ignore" ng-click="ignoreRequest(items.user_id)" id="friend_ignore{{items.user_id}}" href="javascript:void(0);"></a>
                        	<a title="Accept Request" class="friend_accept" id="friend_accept{{items.user_id}}" href="javascript:void(0);" ng-click="acceptRequest(items.user_id)"></a>
                        </div>
                        <div class="clear"></div>
                        
                    </div>
                </div>
                <!-- Friends List ends Here -->                       
                <div class="clear"></div>
            </div>
       
        <div class="clear"></div>
    </div>
 </div>  
<script type="text/javascript">	
	var member_page = 1;
  var groupMemberApp = angular.module('groupMemberApp',[]);
     groupMemberApp.config(function ($httpProvider) {
			$httpProvider.defaults.transformRequest = function(data){
				if (data === undefined) {
					return data;
				}
				return $.param(data);
			}
		});

	groupMemberApp.directive('scroller', function ($window) {
    return {
        restrict: 'A',
        link: function(scope, element, attrs) {
		  var windowEl = angular.element($window); 		  
		  var handler = function() { scope.handler();  }
		  windowEl.on('scroll', scope.$apply.bind(scope, handler));
		 
		}
    };
});	
         
	 
     groupMemberApp.controller('memberController',function($scope, $http){
		$scope.friends_count = <?php echo $friend_count; ?>;
		$scope.group_details = <?php echo json_encode($group_details); ?>;
		$scope.image_paths = <?php echo json_encode($image_folders); ?>;
		$scope.ownerCount = <?php echo $ownerCount; ?>;
		$scope.pending_requests = <?php echo $pending_reguest_count; ?>;
		$scope.categoryImagePath=($scope.image_paths.tag_category!='')?baseurl+"/public/"+$scope.image_paths.tag_category:baseurl+'/public/images/';
		$scope.selectedTab = "All";
		$scope.is_owner = <?php echo $is_owner; ?>;
		$scope.profile_data = <?php echo json_encode($profile_data); ?>;
		 
		$scope.showAllMembers = function(){
			$scope.selectedTab = "All";
			$scope.showMembers();
		}
		$scope.showOwners = function(){
			$scope.selectedTab = "Owners";
			$scope.showMembers();
		}
		$scope.showFriendsMembers = function(){
			$scope.selectedTab = "Friends";
			$scope.showMembers();
		}
		$scope.showPendingRequests = function(){
			$scope.selectedTab = "pending";
			$scope.showMembers();
		}
		
		$scope.ajaxMemberLoader = 0;
		$scope.memberPagination = 0;
		$scope.members = [];
		$scope.loader=0;
		$scope.showMembers = function(){			 
			if($scope.ajaxMemberLoader == 0){
				if($scope.memberPagination==1){
					member_page = member_page+1;
				}else{
					member_page =1;
					$scope.memberPagination=0;
					$scope.loader=1;
				}
				$scope.ajaxMemberLoader =1;
				url  = baseurl+'/groups/getMembers';
				$http.post(url,
				{	
					page:member_page,
					group_id:$scope.group_details.group_id,
					type:$scope.selectedTab,
				},
				{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
				).success(function(data, status, headers, config) {
					$scope.ajaxMemberLoader =0;
					$scope.loader=0;
					if(data.return_array.process_status == 'success'){						
						if(data.return_array.members.length>0){
							if($scope.memberPagination==1){
								$scope.members =$scope.members.concat(data.return_array.members);								
							}else{
								$scope.members =data.return_array.members;
							}
						}
						$scope.memberPagination=0;						
					}else{
						alert(data.return_array.process_info);		
						 
					}				     
				}).error(function(data, status, headers, config) {
					 alert("Error occured. Please try again");
					 $scope.ajaxMemberLoader =0;
				});
			}
		}
		$scope.handler = function() {
			$scope.memberPagination = 1;
			$scope.showMembers();
		}
		$scope.removeuser = function(user_id){
			url  = baseurl+'/groups/removeuser';
			$http.post(url,
			{	
				user_id:user_id,
				group_id:$scope.group_details.group_id,				 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {				 
				if(data.return_array.process_status == 'success'){						
					array_index = $scope.getArrayIndex($scope.members,'user_id',user_id);
					$scope.members.splice( array_index, 1 );
				}else{
					alert(data.return_array.process_info);		
					 
				}				     
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
				 $scope.ajaxMemberLoader =0;
			});
		}
		$scope.promoteadmin = function(user_id){
			url  = baseurl+'/groups/promoteadmin';
			$http.post(url,
			{	
				user_id:user_id,
				group_id:$scope.group_details.group_id,				 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {				 
				if(data.return_array.process_status == 'success'){						
					array_index = $scope.getArrayIndex($scope.members,'user_id',user_id);
					$scope.members[array_index].user_group_role = 1;
				}else{
					alert(data.return_array.process_info);		
					 
				}				     
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
				 
			});
		}
		$scope.revokeadmin = function(user_id){
			url  = baseurl+'/groups/revokeadmin';
			$http.post(url,
			{	
				user_id:user_id,
				group_id:$scope.group_details.group_id,				 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {				 
				if(data.return_array.process_status == 'success'){						
					array_index = $scope.getArrayIndex($scope.members,'user_id',user_id);
					$scope.members[array_index].user_group_role = 0;
				}else{
					alert(data.return_array.process_info);		
					 
				}				     
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
				 
			});
		}
		$scope.getArrayIndex = function(arr_elemnt,key,item){ 
			var incexist = -1;
			for(i=0;i<arr_elemnt.length;i++) {
				if(arr_elemnt[i][key] == item){incexist = i;}
			}
			return incexist;
		};
		$scope.addFriend = function(user){			 
			url  = baseurl+'/user/sentFriendRequest/'+user;
			$http({
			  method: 'POST',
			  url: url
			}).success(function(data, status, headers, config) {				 
				if(data.return_array.process_info==''){
					array_index = $scope.getArrayIndex($scope.members,'user_profile_name',user);
					$scope.members[array_index].is_requested = 1;
				}else{
					alert(data.return_array.process_info);
				}
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
			});
		}
		$scope.rejectFriendRequest  = function(user){			 
			url  = baseurl+'/user/rejectFriendRequest/'+user;
			$http({
			  method: 'POST',
			  url: url
			}).success(function(data, status, headers, config) {
				 
				if(data.return_array.process_info==''){
					array_index = $scope.getArrayIndex($scope.members,'user_profile_name',user);
					$scope.members[array_index].is_friend = 0;
					$scope.members[array_index].is_requested = 0;
					$scope.members[array_index].isPending = 0;
				}else{
					alert(data.return_array.process_info);
				}
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
			});
		}
		$scope.unFriend = function(user){			 
			url  = baseurl+'/user/unFriendRequest/'+user;
			$http({
			  method: 'POST',
			  url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){					 
					array_index = $scope.getArrayIndex($scope.members,'user_profile_name',user);
					$scope.members[array_index].is_friend = 0;
					$scope.members[array_index].is_requested = 0;
					$scope.members[array_index].isPending = 0;
				}else{
					alert(data.return_array.process_info);
				}
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
			});
		}
		$scope.acceptFriendRequest  = function(user){
			 
			url  = baseurl+'/user/acceptFriendRequest/'+user;
			$http({
			  method: 'POST',
			  url: url
			}).success(function(data, status, headers, config) {
				 
				if(data.return_array.process_info==''){
					$scope.members[array_index].is_friend = 1;
					$scope.members[array_index].is_requested = 0;
					$scope.members[array_index].isPending = 0; 
				}else{
					alert(data.return_array.process_info);
				}
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
			});
		}
		$scope.ignoreRequest = function(user_id){
			url  = baseurl+'/groups/ignoreJoinRequest';
			$http.post(url,
			{	
				user_id:user_id,
				group_id:$scope.group_details.group_id,				 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {				 
				if(data.return_array.process_status == 'success'){						
					array_index = $scope.getArrayIndex($scope.members,'user_id',user_id);
					$scope.members.splice( array_index, 1 );
					$scope.pending_requests = ($scope.pending_requests*1)-1;
				}else{
					alert(data.return_array.process_info);		
					 
				}				     
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
				 
			});
		}
		$scope.acceptRequest = function(user_id){
			url  = baseurl+'/groups/acceptJoinRequest';
			$http.post(url,
			{	
				user_id:user_id,
				group_id:$scope.group_details.group_id,				 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {				 
				if(data.return_array.process_status == 'success'){						
					array_index = $scope.getArrayIndex($scope.members,'user_id',user_id);
					$scope.members.splice( array_index, 1 );
					$scope.pending_requests = ($scope.pending_requests*1)-1;
				}else{
					alert(data.return_array.process_info);		
					 
				}				     
			}).error(function(data, status, headers, config) {
				 alert("Error occured. Please try again");
				 
			});
		}
	 });
	 angular.element(document).ready(function() {
   
    angular.bootstrap(document.getElementById("member_container"), ["groupMemberApp"]);


});
</script>
