<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jquery-ui.js','text/javascript'); ?>
<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/planet-top.js','text/javascript'); ?>  
<?php  $this->HeadLink()->appendStylesheet($this->basePath().'/public/css/jquery-ui.css'); ?>
<script>
	var galexy = '<?php echo $planetdetails->galexy_seo_title; ?>';
	var planet = '<?php echo  $planetdetails->group_seo_title; ?>';
</script>
 <script type="text/javascript">
$(function() {   
    
	$("#group_notifications").click(function(){
		
		$("#group_notifications_container").animate({  height:'toggle' });		
		 
	});
});
  </script>
<div class="planet-cover-image">
<?php   if($planetdetails->data_content){ ?>
<img src="<?php echo $this->basePath() ?>/public/album/<?php echo $planetdetails->group_id; ?>/cover/<?php echo $planetdetails->data_content; ?>" alt="" />
<?php }else{ ?>
	<img src="<?php echo $this->basePath() ?>/public/images/planet-cover-default.jpg" alt="" />
<?php } ?>
</div>    
 <div class="view-header">
	<div class="planet-heading"><?php echo $planetdetails->group_title; ?></div>
	<div class="planet-head-right">
            	<div class="galaxy-name"><?php echo $planetdetails->galexy_title; ?></div>
                <div class="planet-location"><?php echo $planetdetails->city; ?></div>
                <div class="planet-members"><?php echo $planetdetails->member_count; ?></div>
				<?php if(!$planetdetails->is_admin && $planetdetails->is_member){ ?>
				<div class="galaxy-quit"><a href="javascript:void(0)" id="quit_group">Quit</a></div>
				<?php } ?>
				<?php if(!empty($approvals)&&count($approvals)>0){ ?>
				<div class="galaxy-notification"><a href="javascript:void(0)" id="group_notifications">Notifications</a>
				<div style="display:none" id="group_notifications_container" >
				<ul>
				<?php 
				$i=0;
				foreach($approvals as $list){ 
					if($list['type'] == 'Member Request'){
						foreach($list['memberRequests'] as $memberRequests){ $i++; ?>
							<li id="list_member_approve_<?php echo $memberRequests['user_id']; ?>">
								<div class="notification-profile-pic">								 
									<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$memberRequests['user_profile_name'])) ?>" class="profile-img-link">
									<?php if($memberRequests['profile_photo']!=''){ ?>
										<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $memberRequests['user_id']; ?>/66x66/<?php echo $memberRequests['profile_photo']; ?>" alt="" />
									<?php }else if($memberRequests['user_register_type'] == 'facebook' && $memberRequests['user_fbid']!=''){ ?>
										<img src="https://graph.facebook.com/<?php echo $memberRequests['user_fbid']; ?>/picture?width=66&&height=66" />
									<?php }else{ ?>
										<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
									<?php } ?>
									</a>
									<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$memberRequests['user_profile_name'])) ?>" class="profile-img-link"><?php echo $memberRequests['user_given_name']; ?></a>
								 </div>
								 <div class="notification-content"> Asking you to join this group</div>
								 <div class="clear"></div>
								<?php if(!empty($group_settings)&&$group_settings->group_joining_questionnaire=='Allow'){ ?>
								 <div id="request_questionnaire">
									<a href="javascript:void(0)" class="view_questionnaire" id="view_questionnaire_<?php echo $memberRequests['user_id']; ?>">View Questionnaire</a>
									<div class="questionnaire_answer_container" style="display:none">
									
									</div>
								 </div>
								 <?php } ?>
								 <div class="notification-actions">
									<a href="javascript:void(0)" id="add_to_members_<?php echo $memberRequests['user_id']; ?>" class="add_to_members blue-butn"> Approve</a>
									<a href="javascript:void(0)" id="ignore_members_<?php echo $memberRequests['user_id']; ?>" class="ignore_members blue-butn"> Ignore</a>
									<a href="javascript:void(0)" id="remove_members_<?php echo $memberRequests['user_id']; ?>" class="remove_members blue-butn"> Remove</a>
								</div>
							</li>
						 
				<?php 	} }
					if($list['type'] == 'Activity Request'){
						foreach($list['activityRequests'] as $activityRequests){ $i++; ?>
							<li id="list_activity_approve_<?php echo $activityRequests['group_activity_id']; ?>">
								<div class="notification-profile-pic">
							 <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activityRequests['user_profile_name'])) ?>" class="profile-img-link">
								<?php if($activityRequests['profile_photo']!=''){ ?>
								<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $activityRequests['user_id']; ?>/66x66/<?php echo $activityRequests['profile_photo']; ?>" alt="" />
								<?php }else if($activityRequests['user_register_type'] == 'facebook' && $activityRequests['user_fbid']!=''){ ?>
									<img src="https://graph.facebook.com/<?php echo $activityRequests['user_fbid']; ?>/picture?width=66&&height=66" />
								<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
								<?php } ?>
								<?php echo $activityRequests['user_given_name']; ?>
								</a>
										</div>
										<div class="notification-content"> 
										Create one activity under this group
										<a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$planetdetails->galexy_seo_title, 'planet_id'=>$planetdetails->group_seo_title,'id'=>$activityRequests['group_activity_id'])) ?>" > View</a>
										</div>
										<div class="clear"></div>
										<div class="notification-actions">
										<a href="javascript:void(0)" id="add_to_activities_<?php echo $activityRequests['group_activity_id']; ?>" class="add_to_activities blue-butn"> Approve</a>
										<a href="javascript:void(0)" id="ignore_activities_<?php echo $activityRequests['group_activity_id']; ?>" class="ignore_activity blue-butn"> Ignore</a>
										<a href="javascript:void(0)" id="remove_activities_<?php echo $activityRequests['group_activity_id']; ?>" class="remove_activity blue-butn"> Remove</a>
										</div>
							</li>
						 
				<?php 	}
					}
					
				} ?>
				</ul>
			</div>
			<div class="notification_counter"><?php echo $i; ?></div>
				</div>
				<?php } ?>
                <div class="clear"></div>
            </div>
			
            <div class="clear"></div>
            <div class="planet-discreption">
                <?php if($planetdetails->is_admin){ ?>
				<div class="planet-settings-menu menu-active"><a href="javascript:void(0)" id="show_hide_settings"><img src="<?php echo $this->basePath() ?>/public/images/settings-icon.png" alt="" /></a></div>
				<?php } ?>
				<div class="planet-text"> <?php echo $planetdetails->group_welcome_message_members; ?></div>
                <div class="planet-text"> <?php echo $planetdetails->group_discription; ?></div>
                <div class="clear"></div>
			</div>
			 <?php if($planetdetails->is_admin){ ?>
			<div class="accordion">
			<?php
				$user_locatioin = unserialize(file_get_contents('http://www.geoplugin.net/php.gp?ip='.$_SERVER['REMOTE_ADDR']));
			?>
				<div class="setting-head">Settings</div>
				<div class="accordion-head"><a href="javascript:void(0);" id="basic_settings">Basic settings</a></div>
				<div class="accordion-options" id="basic_settings_form" style="display:none">
					<div id="basic_errors"></div>
					<div class="settings-field-outer">
						<div class="settings-label2">Name</div>
						<div class="settings-input-small" id="basic_title_field"><?php echo $planetdetails->group_title; ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="title_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="settings-field-outer">
						<div class="settings-label2">Planet picture</div>
						<div class="settings-input-small" id="basic_picture_field">
						<?php   if($planetdetails->data_content){ ?>
						<img src="<?php echo $this->basePath() ?>/public/album/<?php echo $planetdetails->group_id; ?>/medium/<?php echo $planetdetails->data_content; ?>" alt="" />
						<?php }else{ ?> Default
						<?php } ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="picture_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="settings-field-outer">
						<div class="settings-label2">Location</div>
						<div class="settings-input-small" id="basic_location_field"><?php echo $planetdetails->group_location; ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="location_edit">Edit</a></div>
						<div class="clear"></div>
						<div id="map-canvas"></div>
						
						<div class="clear"></div>
						 					
						
					</div>
					<div class="settings-field-outer">
						<div class="settings-label2">Web Address</div>
						<div class="settings-input-small" id="basic_webaddress_field"><?php echo $planetdetails->group_web_address; ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="webaddress_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="settings-field-outer">
						<div class="settings-label2">Description</div>
						<div class="settings-input-small" id="basic_description_field"><?php echo $planetdetails->group_discription; ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="description_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="settings-field-outer">
						<div class="settings-label2">Visitor's welcome message</div>
						<div class="settings-input-small" id="basic_welcome_message_field"><?php echo $planetdetails->group_welcome_message_members; ?></div>
						<div class="field-edit"><a href="javascript:void(0)" id="welcome_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="save-settings" style="display:none" id="basic_button"><a href="javascript:void(0)" class="blue-butn" id="basic_settings_save">Save Settings</a><a href="javascript:void(0)" class="grey-butn" id="basic_settings_cancel" style="color:#333">Cancel</a></div>
				</div>
				<div class="accordion-head"><a href="javascript:void(0);" id="other_settings">Other</a></div>
				<div class="accordion-options" id="other_settings_form" style="display:none">
						
					<div class="settings-field-outer">
						<div class="settings-label2">Membership Roles</div>
						<div class="settings-input-small" id="rolesEditContainer">
						<?php foreach($role_data as $key => $users){  ?>
							<ul class="roles"><li>
								<?php echo $key; ?>
								<ul>
									<?php foreach($users as $row){ ?>
										<li>
										<?php if($row['data_content']!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $row['user_id']; ?>/66x66/<?php echo $row['data_content']; ?>" alt="" />
									<?php }else if($row['user_register_type'] == 'facebook' && $row['user_fbid']!=''){ ?>
										<img src="https://graph.facebook.com/<?php echo $row['user_fbid']; ?>/picture?width=45&&height=45" />
									<?php }else{ ?>	
										<img src="<?php echo $this->basePath(); ?>/public/images/profile-noimage.jpg"  />
									<?php  } ?>
										<?php echo $row['user_given_name']; ?></li>
									<?php } ?>
								</ul>
							</li></ul>
						<?php } ?>
						</div>
						<div class="field-edit"><a href="javascript:void(0)" id="memberroles_edit">Edit</a></div>
						<div class="clear"></div>
					</div>
					<div class="settings-field-outer">
                	<div class="settings-label2">Roll Permissions</div>
                    <div class="settings-input-small" id="rollPermissions_fields">
					<ul><?php foreach($group_role_permissions as $roles){ ?>
					<li><?php echo $roles->group_roles_name; ?></li>
						<?php if($roles->functions){ ?>
							<span>Permissions:</span><ul><?php $arr_functions = explode(",",$roles->functions);
								foreach($group_functions as $functions){	?>					
								 <?php if(in_array($functions->group_functions_id,$arr_functions)) { echo "<li>".$functions->functions."</li>";  } ?>
							<?php	}
							?></ul>
						<?php }else{ ?>
							<span>Permissions:</span> All
						<?php } ?>
					<?php } ?>
					</ul></div>
                    <div class="field-edit"><a href="javascript:void(0)" id="permissions_edit">Edit</a></div>
					<div class="save-settings" style="display:none" id="permission_button">
						<a href="javascript:void(0)" id="permission_save" class="blue-butn">Save Permissions</a>
						<a style="color:#333" id="permission_cancel" class="grey-butn" href="javascript:void(0)">Cancel</a>
					</div>
                    <div class="clear"></div>
                </div>
				
				<div class="settings-field-outer">
                	<div class="settings-label2">Discussions</div>
                    <div class="settings-input-small" id="discussion_settings_field">
						<div class="discussion_first">
						<?php if(!empty($group_settings)&&$group_settings->group_discussion_settings=='Members'){ ?>Any members can start discussion<?php  }else if(!empty($group_settings)&&$group_settings->group_discussion_settings=='Admin') { ?> <?php $i=0;foreach($role_data as $key => $users){  if($i==0){ echo $key;}else{ echo "/".$key; }$i++; }?> can start the descussion <?php }else{ echo "No one can start the discussions"; } ?>
						</div>
						<div class="discussion_hidden" style="display:none">
							Who can start discussion?
							<ul>
								<li><input type="radio" name="radio_discussion_settings" id="members_only" value="Members" <?php if(!empty($group_settings)&&$group_settings->group_discussion_settings=='Members'){ ?> checked="checked" <?php } ?> />Members only </li>
								<li><input type="radio" name="radio_discussion_settings" id="adminonly" value="Admin" <?php if(!empty($group_settings)&&$group_settings->group_discussion_settings=='Admin'){ ?> checked="checked" <?php } ?> /><?php $i=0; foreach($role_data as $key => $users){ if($i==0){ echo $key;}else{ echo "/".$key; }$i++;}?> </li>
								<li><input type="radio" name="radio_discussion_settings" id="members_only" value="no_discussion" <?php if(empty($group_settings)||$group_settings->group_discussion_settings=='None' || $group_settings->group_activity_settings==''){ ?> checked="checked" <?php } ?> />No discussions </li>
							</ul>
							<div>
								<a href="javascript:void(0)" id="discussion_save" class="blue-butn">Save Permissions</a>
								<a style="color:#333" id="discussion_cancel" class="grey-butn" href="javascript:void(0)">Cancel</a>
							</div>
						</div>
					</div>
                    <div class="field-edit"><a href="javascript:void(0)" id="discussion_edit">Edit</a> </div>
                    <div class="clear"></div>
                </div>
				<div class="settings-field-outer">
                	<div class="settings-label2">Activity</div>
                    <div class="settings-input-small">
						<div class="activity_first">
						<?php 
						if(!empty($group_settings)&&$group_settings->group_activity_settings=='Any'){ ?>
							Any members can start activities
						<?php  }else if(!empty($group_settings)&&$group_settings->group_activity_settings=='AdminApproval') { ?> 
						Required approvals from
						<?php $i=0;
						foreach($role_data as $key => $users){
							if($i==0){ 
								echo $key;
							}else{ 
								echo "/".$key; 
							}
							$i++; 
						}?> 
						<?php }else if(!empty($group_settings)&&$group_settings->group_activity_settings=="OnlyAdmin"){
							$i=0;
							foreach($role_data as $key => $users){
								if($i==0){ 
									echo $key;
								}else{ 
									echo "/".$key; 
								}
								$i++; 
							} ?>
							can start Activity.
						<?php }else{ ?> 
							No more activities are allowed.
						<?php } ?>
						</div>
						<div class="activity_hidden" style="display:none">
							Who can start Activity?
							<ul>
								<li><input type="radio" name="radio_activity_settings" id="members_any" value="Any" <?php if(!empty($group_settings)&&$group_settings->group_activity_settings=='Any'){ ?> checked="checked" <?php } ?> />Any Members </li>
								<li><input type="radio" name="radio_activity_settings" id="AdminApproval" value="AdminApproval" <?php if(!empty($group_settings)&&$group_settings->group_activity_settings=='AdminApproval'){ ?> checked="checked" <?php } ?> />Any Member(Approval from <?php $i=0; foreach($role_data as $key => $users){ if($i==0){ echo $key;}else{ echo "/".$key; }$i++;}?> )</li>
								<li><input type="radio" name="radio_activity_settings" id="AdminApproval" value="OnlyAdmin" <?php if(!empty($group_settings)&&$group_settings->group_activity_settings=='OnlyAdmin'){ ?> checked="checked" <?php } ?> /><?php $i=0; foreach($role_data as $key => $users){ if($i==0){ echo $key;}else{ echo "/".$key; }$i++;}?> </li>
								<li><input type="radio" name="radio_activity_settings" id="no_activity" value="None" <?php if(empty($group_settings)||$group_settings->group_activity_settings=='None' || $group_settings->group_activity_settings==''){ ?> checked="checked" <?php } ?> />No Activity </li>
							</ul>
							<div>
								<a href="javascript:void(0)" id="activity_save" class="blue-butn">Save Permissions</a>
								<a style="color:#333" id="activity_cancel" class="grey-butn" href="javascript:void(0)">Cancel</a>
							</div>
						</div>
					</div>
                    <div class="field-edit"><a href="javascript:void(0)" id="activity_edit">Edit</a></div>
                    <div class="clear"></div>
                </div>
				<div class="accordion-head_sub"><a href="javascript:void(0);" id="members_settings">How members can join this planet</a></div>
				<div class="accordion-options_sub" id="members_settings_form" style="display:none">
                    <div class="settings-label-3">Who can join this planet</div>
                    <div class="settings-field-3"><input name="planet_members" type="radio" value="Any" id="anyone" <?php if(!empty($group_settings)&&$group_settings->group_member_join_type=='Any'){ ?> checked="checked" <?php } ?> /> <label for="anyone">Anyone can join the group, there are no restrictions</label></div>
                    <div class="settings-field-3"><input name="planet_members" type="radio" value="AdminApproval" id="approvel" <?php if(!empty($group_settings)&&$group_settings->group_member_join_type=='AdminApproval'){ ?> checked="checked" <?php } ?> /> <label for="approvel">Anyone can try to join, but they must be approved by a group Organizer</label></div>
                    <div class="settings-field-3"><input name="planet_members" type="radio" value="NoOne" id="closed" <?php if(empty($group_settings)||$group_settings->group_member_join_type=='NoOne' || $group_settings->group_member_join_type==''){ ?> checked="checked" <?php } ?>  /> <label for="closed">No one, the group is closed to all new members</label></div>
					<div id="joining_questionnaire_outer" <?php if(empty($group_settings)||$group_settings->group_member_join_type=='NoOne' || $group_settings->group_member_join_type==''){ ?> style="display:none" <?php } ?>>
						<div class="settings-field-3"><input name="chk_questionnaire" type="checkbox" value="1" id="chk_questionnaire" <?php if(!empty($group_settings)&&$group_settings->group_joining_questionnaire=='Allow'){ ?> checked="checked" <?php } ?>  /> <label for="chk_questionnaire">Allow Questionnaire on Join:</label></div>
						<div id="questionnaire_list" <?php if(!empty($group_settings)&&$group_settings->group_joining_questionnaire=='Allow'){ ?> style="display:block" <?php }else{ ?> style="display:none" <?php } ?>>
							<?php $i=0; foreach($questionnaire as $questions){ $i++; ?>
								<div class="settings-field-outer">
									<div class="settings-label2">Question <?php echo $i; ?></div>
									<div class="settings-input-small" id="question_<?php echo $questions->questionnaire_id; ?>"><?php echo $questions->question; ?></div>
									<div class="field-edit" id="question_button_<?php echo $questions->questionnaire_id; ?>"><a href="javascript:void(0)" id="edit_question_<?php echo $questions->questionnaire_id; ?>" class="edit_question">Edit</a></div>
									<div class="clear"></div>
								</div>
							<?php } ?>
							<?php if($i==0){ ?>
								<div>
									<div class="create-fields">
										<div class="create-label">Question1:</div>
										<div class="planet-field"><textarea id="question1" name="question1"></textarea></div>
										<div class="clear"></div> 
										<div class="create-label">Answer Type</div>
										<div class="planet-field">
											<input type="radio"  id="addq1_answer_type1" class="answer_type" name="addq1_answer_type" value="Textarea" checked ="checked" /> Textarea
											<input type="radio"  id="addq1_answer_type2" class="answer_type" name="addq1_answer_type" value="radio" /> Radio buttons
											<input type="radio"  id="addq1_answer_type3" class="answer_type" name="addq1_answer_type" value="checkbox" /> Checkboxes
										</div>
										<div class="clear"></div>										
									</div>
									<div class="clear"></div>
									<div class="create-fields">
										<div class="create-label">Question2:</div>
										<div class="planet-field"><textarea id="question2" name="question2"></textarea></div>
										<div class="clear"></div>
										<div class="create-label">Answer Type</div>
										<div class="planet-field">
											<input type="radio"  id="addq2_answer_type1" class="answer_type" name="addq2_answer_type" value="Textarea" checked ="checked" /> Textarea
											<input type="radio"  id="addq2_answer_type2" class="answer_type" name="addq2_answer_type" value="radio" /> Radio buttons
											<input type="radio"  id="addq2_answer_type3" class="answer_type" name="addq2_answer_type" value="checkbox" /> Checkboxes
										</div>
										<div class="clear"></div>
									</div>
									<div class="clear"></div>
									<div class="create-fields">
										<div class="create-label">Question3:</div>
										<div class="planet-field"><textarea id="question3" name="question3"></textarea></div>
										<div class="clear"></div>
										<div class="create-label">Answer Type</div>
										<div class="planet-field">
											<input type="radio"  id="addq3_answer_type1" class="answer_type" name="addq3_answer_type" value="Textarea" checked ="checked" /> Textarea
											<input type="radio"  id="addq3_answer_type2" class="answer_type" name="addq3_answer_type" value="radio" /> Radio buttons
											<input type="radio"  id="addq3_answer_type3" class="answer_type" name="addq3_answer_type" value="checkbox" /> Checkboxes
										</div>
										<div class="clear"></div>
									</div> 
									<div class="clear"></div>
									<div class="create-fields">
										<input type="button" id="add_question" value="Add" class="blue-butn2" />
										<div class="clear"></div>
									</div> 
								</div>
							<?php } ?>
						</div> 
					</div>
                    <div class="settings-label-3">New member emails</div>
                    <div class="settings-field-3">
                    	<p>Welcome message to new members</p>
                        <p>New members receive an automatic email confirmation when they join this Meetup. You can add your own message to introduce yourself and <br /> encourage new members to RSVP for your next Meetup or fill out their profile.</p>
                    </div>
                    <div class="settings-field-3">
                    	<textarea name="welcome_email" id="welcome_email"><?php if(isset($group_settings->group_welcome_email)){ echo $group_settings->group_welcome_email; } ?></textarea>
                    </div>
                    <div class="save-settings" style="padding-left:0; padding-top:10px;"><a href="javascript:void(0)" id="members_join_settings" class="blue-butn">Submit</a></div>
                    
                    
                </div>
				<div class="accordion-head_sub"><a href="javascript:void(0);" id="tag_settings">About (tags)</a></div>
				 <div class="accordion-options_sub" id="tag_settings_form" style="display:none">
                	<div class="create-fields">
                        	<div class="create-label-2">Tags:"Explain what is intrest tags?"</div>
                        </div>
                        <div class="create-fields">
                        	<div class="create-label-2"><span>Whats your planet about?</span></div>
                        </div>
                        <div class="create-fields">
                        	<div class="create-label-2">Tags <span>categorize</span> and <span>describe</span> what your Planet is about in a word or two.</div>
                        </div>
                        <div class="create-fields">
                        	<div class="create-label-2"><span>Why are Tags important? </span></div>
                        </div>
                        <div class="create-fields">
                        	<div class="create-label-2">Well-picked  topics help the right members find your Group. Your Group will be listed in our directory under each Tag you choose.</div>
                        </div>
                        <div class="interest-tags planet-tags">
                            Your Planet Tags:
							<div id="group_tags">
							<?php foreach($groupTag as $tags){ ?>
                            <a id="<?php echo $tags->tag_id; ?>" class="add-option" href="javascript:void(0)"><?php echo $tags->tag_title; ?> </a> 
							<?php } ?>
                            </div>
                            <a href="javascript:void(0)" id="clear_all_tags" class="grey-butn">Clear tags</a>
                             
                        </div>
                        <div class="clear"></div>
                        <div class="tag-search">
                        	<input name="tag_search" id="tag_search" type="text" placeholder="Search tag" />
                            <input name="" id="btn_search_tag" type="image" src="<?php echo $this->basePath() ?>/public/images/search-butn.png" />
                        </div>
                        <div class="interest-tags planet-tags" id="interest-tags">
							<?php foreach($popularTags as $tags){ ?>
								<a id="<?php echo $tags->tag_id; ?>" class="add-option" href="javascript:void(0)"><?php echo $tags->tag_title; ?> </a> 
							<?php } ?>
                             
                        </div>
                        <div class="clear"></div>
                        <div class="load-more-butn" style="text-align:left; padding-top:0;">
                    		<a href="javascript:void(0)" class="blue-butn" id="tag_submit">Submit</a>
                    	</div>
                </div>
				<div class="accordion-head_sub"><a href="javascript:void(0);" id="privacy_settings">Privacy</a></div>
				<div class="accordion-options_sub" id="privacy_settings_form" style="display:none">
                	<div class="settings-label-3"><input name="privacy" type="radio" value="Public" id="public" <?php if(!empty($group_settings)&&$group_settings-> group_privacy_settings=='Public'){ ?> checked="checked" <?php } ?> <?php if(empty($group_settings)||$group_settings->group_privacy_settings==''){ ?>checked="checked" <?php } ?>/> <label for="public">Public</label></div>
                    <div class="settings-field-3" style="padding-left:25px; padding-top:0;">Show all information to members and non-members. Get more members who are better fit!</div>
                    <div class="settings-label-3"><input name="privacy" type="radio" value="Private" id="private" <?php if(!empty($group_settings)&&($group_settings-> group_privacy_settings=='Limited'||$group_settings->group_privacy_settings=='NoInfo')){ ?> checked="checked" <?php } ?>   /> <label for="private">Private</label></div>
                    <div class="settings-field-3" style="padding-left:25px; padding-top:0;">Show non-members limeted Planet information and</div>
                    <div class="private-sub-fields" <?php if(empty($group_settings)||$group_settings->group_privacy_settings=='Public'||$group_settings->group_privacy_settings==''){ ?> style="display:none" <?php } ?>  >
						 
                    	<div class="settings-label-3"><input name="privacy_sub" type="radio" value="Limited" <?php if(!empty($group_settings)&&$group_settings-> group_privacy_settings=='Limited'){ ?> checked="checked" <?php } ?>   id="event_info" /> <label for="event_info">Show limited Planet Event information</label></div>
                        <div class="settings-field-3" style="padding-top:0; padding-left:25px;">Shown: Activity name, date, time and atendee count.<br />Hidden: Activity location, description, member information and photos</div>
                        <div class="settings-label-3"><input name="privacy_sub" type="radio" value="NoInfo" id="acti_info" <?php if(!empty($group_settings)&&$group_settings-> group_privacy_settings=='NoInfo'){ ?>   checked="checked" <?php } ?>  /> <label for="acti_info">Show no Planet information</label></div>
                        <div class="settings-field-3" style="padding-top:0; padding-left:25px;">Keep you Activity as hidden as possible</div>
						 
                   </div>
                   <div class="load-more-butn" style="text-align:left; padding-top:0;">
                        <a href="javascript:void(0)" class="blue-butn" id="privacy_settings_save">Submit</a>
                   </div>
                </div>
				<div class="accordion-head_sub"><a href="javascript:void(0);" id="visibility_settings">Group Status</a></div>
				<div class="accordion-options_sub" id="visibility_settings_form" style="display:none">
                	 <div class="create-fields">
						<div class="settings-label2">Group Status :</div>
						<div class="settings-input-small" id="visiblity_status"><?php if($planetdetails->group_status){ echo "Active"; }else{ echo "Deactive"; } ?></div>
                        	 
							 <div class="field-edit"><a href="javascript:void(0)" id="visibility_edit">Edit</a></div>
                        </div>
                   <div class="load-more-butn" style="text-align:left; padding-top:0;display:none" id="visibility_button">
                        <a href="javascript:void(0)" class="blue-butn" id="visibility_settings_save">Submit</a>
                   </div>
                </div>
				</div>
			</div>
			<?php } ?>
 </div>
 
 <div id="all-members-dialog" style="display:none"></div>
   <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 <style>
	#map-canvas, #activity_map{
  height: 400px;

  border: 1px solid #999;
  -moz-box-shadow:    0px 0px 5px #ccc;
  -webkit-box-shadow: 0px 0px 5px #ccc;
  box-shadow:         0px 0px 5px #ccc;
}
 </style>
 <script>
  <?php if($planetdetails->y2m_group_location_lat!=''&&$planetdetails->y2m_group_location_lng!=''){ ?>
		var current_lat = <?php echo $planetdetails->y2m_group_location_lat; ?>;
		var current_lng = <?php echo $planetdetails->y2m_group_location_lng; ?>;
	 <?php }else{  ?>
		var current_lat = 25.271139000000000000;
		var current_lng =55.307485000000040000;
	 <?php } ?>
var geocoder;
var map;
var marker;
var mapselected = 'map1';
// initialise the google maps objects, and add listeners
function gmaps_init(){

  // center of the universe
  var latlng = new google.maps.LatLng(current_lat,current_lng);

  var options = {
    zoom: 7,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP,

  };

  // create our map object
  if(mapselected=='map1')
  map = new google.maps.Map(document.getElementById("map-canvas"), options);
  else
   map = new google.maps.Map(document.getElementById("activity_map"), options);

  // the geocoder object allows us to do latlng lookup based on address
  geocoder = new google.maps.Geocoder();
	 

  // the marker shows us the position of the latest address
  marker = new google.maps.Marker({
    map: map,
	icon: "<?php echo $this->basepath(); ?>/public/images/rocket2-icon.png",
    draggable: true
  });
marker.setPosition(latlng);
  // event triggered when marker is dragged and dropped
  google.maps.event.addListener(marker, 'dragend', function() {
    geocode_lookup( 'latLng', marker.getPosition() );
  });

  // event triggered when map is clicked
  google.maps.event.addListener(map, 'click', function(event) {
    marker.setPosition(event.latLng)
    geocode_lookup( 'latLng', event.latLng  );
  });

  $('#gmaps-error').hide();
}

// move the marker to a new position, and center the map on it
function update_map( geometry ) {
  map.fitBounds( geometry.viewport )
  marker.setPosition( geometry.location )
}

// fill in the UI elements with new position data
function update_ui( address, latLng ) {
if(mapselected=='map1'){
  $('#location').autocomplete("close");
  $('#location').val(address);
  }else{
   $('#address').autocomplete("close");
  $('#address').val(address);
  }
  geo_latitude = latLng.lat(); 
  geo_longitude = latLng.lng(); 
  //$('#gmaps-output-latitude').html(latLng.lat());
  //$('#gmaps-output-longitude').html(latLng.lng());
}

// Query the Google geocode object
//
// type: 'address' for search by address
//       'latLng'  for search by latLng (reverse lookup)
//
// value: search query
//
// update: should we update the map (center map and position marker)?
function geocode_lookup( type, value, update ) {
  // default value: update = false
  update = typeof update !== 'undefined' ? update : false;

  request = {};
  request[type] = value;

  geocoder.geocode(request, function(results, status) {
    $('#gmaps-error').html('');
    $('#gmaps-error').hide();
    if (status == google.maps.GeocoderStatus.OK) {
      // Google geocoding has succeeded!
      if (results[0]) {
        // Always update the UI elements with new location data
        update_ui( results[0].formatted_address,
                   results[0].geometry.location )

        // Only update the map (position marker and center map) if requested
        if( update ) { update_map( results[0].geometry ) }
      } else {
        // Geocoder status ok but no results!?
        $('#gmaps-error').html("Sorry, something went wrong. Try again!");
        $('#gmaps-error').show();
      }
    } else {
      // Google Geocoding has failed. Two common reasons:
      //   * Address not recognised (e.g. search for 'zxxzcxczxcx')
      //   * Location doesn't map to address (e.g. click in middle of Atlantic)

      if( type == 'address' ) {
        // User has typed in an address which we can't geocode to a location
        $('#gmaps-error').html("Sorry! We couldn't find " + value + ". Try a different search term, or click the map." );
        $('#gmaps-error').show();
      } else {
        // User has clicked or dragged marker to somewhere that Google can't do a reverse lookup for
        // In this case we display a warning, clear the address box, but fill in LatLng
        $('#gmaps-error').html("Woah... that's pretty remote! You're going to have to manually enter a place name." );
        $('#gmaps-error').show();
        update_ui('', value)
      }
    };
  });
};

// initialise the jqueryUI autocomplete element
function autocomplete_init() {
	if(mapselected=='map1'){
  $("#location").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }else{
	  $("#address").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }
if(mapselected=='map1'){
  // triggered when user presses a key in the address box
  $("#location").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#location').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#location').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#location').autocomplete("enable")
    }
  });
  }
  else{
	$("#address").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#address').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#address').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#address').autocomplete("enable")
    }
  });
  }
}; // autocomplete_init
 
		
</script>
 