
 <?php 
 $this->HeadScript()->appendFile($this->basePath().'/public/js/members.js','text/javascript');
 if(isset($error) && count($error)) { ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php }else{ ?>
<?php echo $this->groupTopWidget; ?> 
 <div class="profile-tabs2">
	<div id="tabs">
		<div class="tabs-outer tabs">
			<ul> 
				<li><a href="<?php echo $this->url('groups/planethome',array('group_id'=>$planetdetails->galexy_seo_title,'planet_id'=>$planetdetails->group_seo_title));?>" class="activity_tab">Activities</a></li>
				<?php if($planetdetails->is_member){ ?> <li><a href="<?php echo $this->url('groups/group-discussion', array('action' => 'subgroupdetailwithdiscussion', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="discuss_tab">Discussion</a></li>
				<li><a href="<?php echo $this->url('groups/group-media', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="media_tab">Media</a></li> <?php } ?>
				<li class="active"><a href="<?php echo $this->url('groups/group-members', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="member_tab">Members</a></li>
			</ul>
            <div class="clear"></div>
         </div>
	
	
	<div class="tab-sub">
		<div class="tab-sub">
			<div class="sub_tabs-outer"> 
						<span class="members-count">  Members:<?php echo $members_count; ?> </span>
						 <div class="member-search">
							<input type="text" placeholder="Search Members" id="member-search" name="member-search">
							<input type="image" src="<?php echo $this->basePath(); ?>/public/images/search-butn.png" id="btn_search_members" name="">
						</div>
			</div>
			 <div class="clear"></div>
		</div>
	</div>
	<div id="tabs-1"> 
	<div id="members_list">
	<?php 
	if(isset($groupUsersList) && count($groupUsersList)) {
					foreach($groupUsersList as $usersdata){ ?>
	<div class="connection-list-outer" id="connection-list-outer<?php echo $usersdata->user_id; ?>">
		<div class="connection-img profile-image-comn">
			<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$usersdata->user_profile_name)) ?>" class="profile-img-link">
			<?php if($usersdata->profile_photo!=''){ ?>
			<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $usersdata->user_id ?>/66x66/<?php echo $usersdata->profile_photo; ?>" alt="" />
			<?php }else if($usersdata->user_register_type == 'facebook' && $usersdata->user_fbid!=''){ ?>
				<img src="https://graph.facebook.com/<?php echo $usersdata->user_fbid; ?>/picture?width=66&&height=66" />
			<?php }else{ ?>
			<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
			<?php } ?>
			</a>
        </div>
		<div class="connection-name"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$usersdata->user_profile_name)) ?>"><?php echo $usersdata->user_given_name; ?></a></div>
		<div class="connection-status" id="connection-status_<?php echo $usersdata->user_id; ?>"><?php if($user_id!=$usersdata->user_id ){ 
			if($usersdata->is_friend){ ?>		
			<span>Friends</span>
			<?php }else if($usersdata->is_requested){
				echo "Already requested ";
			}else if($usersdata->get_request){
				echo '<a href="javascript:void(0)" class="blue-butn accept_friend" id="accept_friend_'.$usersdata->user_id.'">Accept request</a>';
			}else{
				echo '<a href="javascript:void(0)" class="blue-butn add_friend" id="add_friend_'.$usersdata->user_id.'">Add friend</a>';
			}
			if($member_delete_permission){
				echo '<a href="javascript:void(0)" class="grey-butn remove_user" id="remove_'.$usersdata->user_id.'">Delete</a>';
				echo '<div id="suspend_outer_'.$usersdata->user_id.'" class="suspend_user_container">';
				if($usersdata->user_group_status == 2){
					echo '<a href="javascript:void(0)" class="grey-butn remove_suspensssion" id="remove_suspensssion_'.$usersdata->user_id.'">Remove Suspenssion</a>';
				}else{
					echo '<a href="javascript:void(0)" class="grey-butn suspend_user" id="suspend_'.$usersdata->user_id.'">Suspend</a>';
				}
				echo '</div>';
			}
		} ?></div>
		<div class="clear"></div>
		<?php if(!empty($group_settings)&&$group_settings->group_joining_questionnaire=='Allow'){ ?>
		 <div id="request_questionnaire">
			<a href="javascript:void(0)" class="view_questionnaire_member" id="view_questionnaire_<?php echo $usersdata->user_id; ?>">View Questionnaire</a>
			<div id="questionnaire_answer_container_<?php echo $usersdata->user_id; ?>" class="questionnaire_answer_container_member" style="display:none">
			
			</div>
			<div class="clear"></div>
		 </div>
		 <div class="clear"></div>
		 <?php } ?>
	</div>



	 

<?php } }  ?>
</div>
<div class="ajax_loader"></div>
 <div class="clear"></div>
 </div>
</div>
 </div>
 <?php } ?>