<?php if($planetSuggestions&&!empty($planetSuggestions)){ ?> 
<div class="suggestion-head">Planet Suggestions</div>
<div class="suggestion-outer">
				<?php
				$i=0;
				foreach($planetSuggestions as $planets){ $i++; ?>			 
            	<div class="sugg-planet-outer">
                	<div class="suggest-img">
						<?php if($planets->data_content!=''){ ?>
							<img src="<?php echo $this->basePath() ?>/public/datagd/galexy/<?php echo $planets->data_content; ?>" alt="" />
						<?php }else{ ?>
							<img src="<?php echo $this->basePath() ?>/public/images/galaxy-noimg.jpg" alt="" />
						<?php } ?>
					</div>
                    <div class="suggest-details">
                    	<?php  echo $planets->group_title; ?>
                        <span><?php  echo $planets->member_count; ?> engaged</span>
                        <div class="seemore-butn">
                        	<a href="<?php echo $this->url('groups/planethome',array('group_id'=>$planets->parent_seo_title,'planet_id'=>$planets->group_seo_title));?>">See planets</a>
                        	<div class="clear"></div>
                        </div>
                    </div>
                </div>
				<?php } ?>         
                <?php if($i==0){ ?>
					<script>
					$(".suggestion-head").hide();
					</script>
				<?php } ?>
                <div class="clear"></div>
            </div>
			<?php } ?>