<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jquery-ui-timepicker-addon.js','text/javascript'); ?>
<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/planet-view.js','text/javascript'); ?>
<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jMonthCalendar.js','text/javascript'); ?>

<script>
	var galexy = '<?php echo $planetdetails->galexy_seo_title; ?>';
	var planet = '<?php echo  $planetdetails->group_seo_title; ?>';
</script>
<script type="text/javascript">
$(function() {   
    
	$("#add_activity").click(function(){
		
		$(".new-activity-container").animate({  height:'toggle' });		
		mapselected = 'map2';
		gmaps_init();
		autocomplete_init();
	});
	 $('#group_activity_start_timestamp').datetimepicker({   
 beforeShow: function() {
        setTimeout(function(){
            $('.ui-datepicker').css('z-index', 99999);
        }, 0);
    } , 
	dateFormat: 'yy-mm-dd', 
	timeFormat: 'hh:mm:ss',
    //minDate: 0
	
	}); 
	$("#tab_upcoming").click(function(){
		$("#tabs_sub-1").show();
		$("#tabs_sub-2").hide();
		$("#tabs_sub-3").hide();
		$("#tab_upcoming").parent().addClass("active");
		$("#tab_past").parent().removeClass("active");
		$("#tab_calendar").parent().removeClass("active");
	});
	$("#tab_past").click(function(){
		$("#tabs_sub-1").hide();
		$("#tabs_sub-2").show();
		$("#tabs_sub-3").hide();
		$("#tab_upcoming").parent().removeClass("active");
		$("#tab_past").parent().addClass("active");
		$("#tab_calendar").parent().removeClass("active");
	});
	$("#tab_calendar").click(function(){
		$("#tabs_sub-1").hide();
		$("#tabs_sub-2").hide();
		$("#tabs_sub-3").show();
		$("#tab_upcoming").parent().removeClass("active");
		$("#tab_past").parent().removeClass("active");
		$("#tab_calendar").parent().addClass("active");
	});	
});
</script>
  <?php echo $this->groupTopWidget; ?>  
 <?php if($planetdetails->is_member||!isset($group_settings->group_privacy_settings)||$group_settings->group_privacy_settings != 'NoInfo'){ ?>
 <div class="profile-tabs2">
	<div id="tabs">
		<div class="tabs-outer tabs">
			<ul> 
				<li class="active"><a href="<?php echo $this->url('groups/planethome',array('group_id'=>$planetdetails->galexy_seo_title,'planet_id'=>$planetdetails->group_seo_title));?>" class="activity_tab">Activities</a></li>
				<?php if($planetdetails->is_member){ ?> <li><a href="<?php echo $this->url('groups/group-discussion', array('action' => 'subgroupdetailwithdiscussion', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="discuss_tab">Discussion</a></li>
				<li><a href="<?php echo $this->url('groups/group-media', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="media_tab">Media</a></li> <?php } ?>
				<li><a href="<?php echo $this->url('groups/group-members', array('action' => 'index', 'group_id'=>$planetdetails->galexy_seo_title, 'sub_group_id'=>$planetdetails->group_seo_title)) ?>" class="member_tab">Members</a></li>
			</ul>
            <div class="clear"></div>
         </div>
		 <div id="tabs-1">
			<div class="tab-sub">
				<div class="sub_tabs-outer">
					<ul>
						<li class="active"><a href="javascript:void(0)" id="tab_upcoming">Upcoming</a></li>
				<?php if($planetdetails->is_member){ ?>		<li><a href="javascript:void(0)" id="tab_past">Past</a></li>
						<li><a href="javascript:void(0)" id="tab_calendar">Calendar</a></li> <?php } ?>
					</ul>
					<div class="add-activity-butn"><?php if($planetdetails->is_member&&$activity_permission){ ?><a href="javascript:void(0);" class="blue-butn" id="add_activity">Add new activity</a><?php }else{
				if(isset($group_settings)&&!empty($group_settings)&&$group_settings->group_member_join_type!='NoOne'&&!$is_request&&!$planetdetails->is_member){
				?><a href="javascript:void(0);" class="blue-butn" id="join_group">Join this group</a> <?php } } ?></div>
				<div class="clear"></div>
				</div>
                
				<?php if($planetdetails->is_member&&$activity_permission){ ?>
				 <div class="new-activity-container" style="display:none">
                      		<div class="activity-left">
                            	<div class="settings-label-3">Event Name</div>
                              <div class="settings-field-4"><input name="activity_title" id="activity_title" type="text" placeholder="Name" /></div>
                                <div class="settings-label-3">Description</div>
                                <div class="settings-field-4">
                                  <textarea name="activity_description" id="activity_description" placeholder="Name" placeholder="Description"></textarea>
                                </div>
                                <div class="interest-tags planet-tags">
                                    Tags:
									<div id="activty_tags">
									
									</div>
                                    <a href="javascript:void(0)" id="clear_all_tags_addactivity" class="grey-butn">Clear tags</a>
                                    
                                </div>
                                <div class="clear"></div>
                                <div class="tag-search">
                                    <input name="tag_search_for_activity" id="tag_search_for_activity" type="text" placeholder="Search tag" />
                                    <input name="" type="image" id="btn_search_tag_for_activity" src="<?php echo $this->basePath(); ?>/public/images/search-butn.png" />
                                </div>
                                <div class="interest-tags planet-tags" id="group_tags_for_activity">
									<?php foreach($LimitedgroupTag as $tags){ ?>
                                   <a href="javascript:void(0)" class="add-option" id="<?php echo $tags->tag_id; ?>"><?php echo $tags->tag_title; ?> </a>   
								   <?php } ?>
                                </div>
                            </div>
                            <div class="activity-right">
                            	<div class="place-field"><input name="" id="address" type="text" placeholder="Place" /></div>
								<div id="activity_map"  style="width:430px; height:300px"></div>
                                <div class="time-and-date">
                                	 
                                    <div class="date-activity"><input name="group_activity_start_timestamp" id="group_activity_start_timestamp" type="text" /></div>
                                    <div class="clear"></div>
                                </div>
                                <div class="activity-friends-outer">
									<div id="place-field"><input type="radio" name="user_invite" id="public" value="public" checked="checked" />Public <input type="radio" name="user_invite" id="invited_users" value="invited" />Invited users only </div>
									<div class="clear"></div>
									<div id="membersZone"></div>
                                	<div class="friend-list" style="display:none">
                                    	 
                                        
                                        <div class="clear"></div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                               <div class="clear"></div>
                            </div>
                            <div class="add-activity-actions">
                            	<a href="javascript:void(0)" id="save_activity" class="blue-butn">Add new</a>
                                <a href="javascript:void(0);" class="grey-butn" id="cancel_activity" style="color:#888888;">Cancel</a>
                            </div>
                            <div class="clear"></div>
                      </div> <?php } ?>
				<div id="tabs_sub-1"> 
						<div id="activity_list">
							<?php foreach($upcoming_activities as $activities){ ?>
                        	<div class="activity-outer">
                            	<div class="activity-profileimg profile-image-comn">
								<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>" class="profile-img-link">
								<?php  if($activities['profile_photo']!=''){ ?>								 
								<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $activities['user_id']; ?>/66x66/<?php echo $activities['profile_photo']; ?>" alt="" />
								<?php }else if($activities['user_register_type'] == 'facebook' && $activities['user_fbid']!=''){ ?>
									<img src="https://graph.facebook.com/<?php echo $activities['user_fbid']; ?>/picture?width=66&&height=66" />
								<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
								<?php } ?>
								</a>
								</div>
                                <div class="activity-main-outer">
                                	<div class="activity-author"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>" class="profile-img-link"><?php echo $activities['user_given_name']; ?></a></div>
                                    <div class="activity-text"><a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$planetdetails->galexy_seo_title, 'planet_id'=>$planetdetails->group_seo_title,'id'=>$activities['group_activity_id'])) ?>"><?php echo $activities['group_activity_title']; ?><span> on <?php echo date("F d,g A",strtotime($activities['group_activity_start_timestamp'])) ?> .</span></a></div>
                                    <div class="activity-details_planet">
										<?php if($planetdetails->is_member){ ?>
										 <div class="activity-text">
											<?php echo $activities['group_activity_content']; ?>
										 </div>
										 <?php } ?>
                                        <div class="like-comment-outer">
                                            <div class="likes" id="likes_<?php echo $activities['group_activity_id']; ?>">
											<?php if($activities['activity_like']->is_liked){  ?>
												<?php if($planetdetails->is_member){ ?>
													<a href="javascript:void(0)"  class="activity-unlikes" id="<?php echo $activities['group_activity_id']; ?>"  ><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />  </a>
												<?php }else{  ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /> 
												<?php }
											}else{ ?> 
												<?php if($planetdetails->is_member){ ?>	
													<a href="javascript:void(0)" id="<?php echo $activities['group_activity_id']; ?>" class="activity-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />  </a>
												<?php }else{ ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
												<?php } ?>
											<?php } ?>
											<?php if($activities['activity_like']->likes_counts){echo $activities['activity_like']->likes_counts;} ?>
											</div>
                                            <div class="likes"><a href="javascript:void(0)"><img src="<?php echo $this->basePath(); ?>/public/images/comments-icon.png" alt="" /></a> <?php if($activities['comment_count']){echo $activities['comment_count'];} ?> <span><a href="javascript:void(0)">Comment</a></span></div>
                                            <div class="clear"></div>
                                        </div>
										<?php if($planetdetails->is_member){ ?>
                                        <div class="activity-location"><?php echo $activities['group_activity_location']; ?></div>
                                         <?php } ?>
                                        <div class="clear"></div>
                                    </div>
                                </div>
								
                                <div class="join-activity-outer">
									<?php if($planetdetails->is_member){ ?>
                                	<div class="activity-rocket<?php if($activities['is_member']){ echo "-member"; } ?>" id="joinactivity_rocket_<?php echo $activities['group_activity_id']; ?>"></div>
                    				<div class="join-ride-butn" id="joinactivity_outer_<?php echo $activities['group_activity_id']; ?>">
									<?php if($activities['is_member']){   ?>
										<a href="javascript:void(0)" class="blue-butn quitactivity" id="quitactivity_<?php echo $activities['group_activity_id']; ?>">Quit the ride</a>
									<?php }else{ ?>
									<a href="javascript:void(0)" class="blue-butn joinactivity" id="joinactivity_<?php echo $activities['group_activity_id']; ?>">Join the ride</a>
									<?php } ?>
									</div>
									<?php } ?>
                                </div>
                                <div class="activity-members-outer">
									<?php if($planetdetails->is_member){ ?>
                                	<div class="members-head">Members on board  <a href="javascript:void(0)" class="membersonboard" id="<?php echo $activities['group_activity_id']; ?>"><?php echo $activities['member_count']; ?></a></div>
									
                                    <div class="members-list">
									<?php foreach($activities['members'] as $members){ ?>
                                    	<div class="activity-member profile-image-comn">
											<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>" class="profile-img-link">
											<?php if($members->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $members->user_id ?>/66x66/<?php echo $members->profile_photo; ?>" alt="" />
											<?php }else if($members->user_register_type == 'facebook' && $members->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $members->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
                                            <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>"><?php echo $members->user_given_name; ?></a>
                                        </div>
										<?php } ?>
                                        
                                        <div class="clear"></div>
                                    </div>
									<?php } ?>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="activity-comments">
								<div id="loadmore_<?php echo $activities['group_activity_id']; ?>"><?php if($activities['comment_count']>2){ ?><a href="javascript:void(0)" id="<?php echo $activities['group_activity_id']; ?>" class="loadmore_comments">View <span id="comment_count_<?php echo $activities['group_activity_id']; ?>"><?php echo $activities['comment_count']-2 ;?></span> more comments</a> <?php } ?></div>
								<div id="comment_area<?php echo $activities['group_activity_id']; ?>">
								<?php  
								$arr_comments = array();
								foreach($activities['comments'] as $comments){
									$arr_comments[] = $comments;
								}
								$newcommnt =  array_reverse($arr_comments);
								foreach($newcommnt as $comments){  
								?>
                            	<div class="comments-outer" id="comments-outer-<?php echo $comments->comment_id ?>">
                                    <div class="comment-profil-img">
										<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>" class="profile-img-link">
											<?php if($comments->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $comments->user_id ?>/66x66/<?php echo $comments->profile_photo; ?>" alt="" />
											<?php }else if($comments->user_register_type == 'facebook' && $comments->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $comments->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
										</div>
                                    <div class="comment-text comment-text2" >
                                        <span><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>"><?php echo $comments->user_given_name; ?></a></span>
                                         <div id="comment_text_<?php echo $comments->comment_id; ?>"> <?php echo $comments->comment_content; ?></div>
										 
										<div><?php if($comments->user_id == $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="edit_comment_<?php echo $comments->comment_id; ?>" class="edit_comment">Edit</a><?php } ?>&nbsp;<?php if($comments->user_id == $this->layout()->identity->user_id || $is_admin ||$activities['group_activity_owner_user_id'] == $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="delete_comment_<?php echo $comments->comment_id; ?>" class="delete_comment">Delete</a><?php } ?></div>
										 
										
                                        <div class="activity-comment-like" id="comments_likes<?php echo $comments->comment_id; ?>">
										<?php if($comments->islike){ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-unlikes"><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />
											<?php } ?>
										<?php }else{ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
											<?php } ?>
										<?php }?>
										<?php echo $comments->likes_count; ?>
										</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
								<?php } ?>
								</div>
                                 <?php if($planetdetails->is_member){ ?>
                                <div class="activity-add-comment">
                                	<textarea name="comment" id="comment_<?php echo $activities['group_activity_id']; ?>" class="activity_comments" placeholder="Comment"></textarea>
                                </div>
								<?php } ?>
                            </div>
							<?php } ?>
						 </div>
							<div id="activity_loadmore_container" class="btn-loadmore">
								<a href="javascript:void(0)" id="activity_loadmore" >Load more</a>
							</div>
						
                      </div>
					  <div id="tabs_sub-2" style="display:none">
						<div id="past_activity_list">
							<?php foreach($past_activities as $activities){?>
                        	<div class="activity-outer">
                            	<div class="activity-profileimg profile-image-comn">
								<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>" class="profile-img-link">
								<?php  if($activities['profile_photo']!=''){ ?>								 
								<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $activities['user_id']; ?>/66x66/<?php echo $activities['profile_photo']; ?>" alt="" />
								<?php }else if($activities['user_register_type'] == 'facebook' && $activities['user_fbid']!=''){ ?>
									<img src="https://graph.facebook.com/<?php echo $activities['user_fbid']; ?>/picture?width=66&&height=66" />
								<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
								<?php } ?>
								</a>
								</div>
                                <div class="activity-main-outer">
                                	<div class="activity-author"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>"><?php echo $activities['user_given_name']; ?></a></div>
                                    <div class="activity-text"><a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$planetdetails->galexy_seo_title, 'planet_id'=>$planetdetails->group_seo_title,'id'=>$activities['group_activity_id'])) ?>"><?php echo $activities['group_activity_title']; ?><span> on <?php echo date("F d,g A",strtotime($activities['group_activity_start_timestamp'])) ?> .</span></a></div>
                                    <div class="activity-details_planet">
                                        <div class="like-comment-outer">
                                            <div class="likes" id="likes_<?php echo $activities['group_activity_id']; ?>">
											<?php if($activities['activity_like']->is_liked){  ?>
												<?php if($planetdetails->is_member){ ?>
													<a href="javascript:void(0)"  class="activity-unlikes" id="<?php echo $activities['group_activity_id']; ?>"  ><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />  </a>
												<?php }else{  ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /> 
												<?php }
											}else{ ?> 
												<?php if($planetdetails->is_member){ ?>	
													<a href="javascript:void(0)" id="<?php echo $activities['group_activity_id']; ?>" class="activity-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />  </a>
												<?php }else{ ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
												<?php } ?>
											<?php } ?>
											<?php if($activities['activity_like']->likes_counts){echo $activities['activity_like']->likes_counts;} ?>
											</div>
                                            <div class="likes"><a href="javascript:void(0)"><img src="<?php echo $this->basePath(); ?>/public/images/comments-icon.png" alt="" /></a> <?php if($activities['comment_count']){echo $activities['comment_count'];} ?> <span><a href="javascript:void(0)">Comment</a></span></div>
                                            <div class="clear"></div>
                                        </div>
                                        <div class="activity-location"><?php echo $activities['group_activity_location']; ?></div>
                                         
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                <div class="join-activity-outer">
                                	<div class="activity-rocket<?php if($activities['is_member']){ echo "-member"; } ?>" id="joinactivity_rocket_<?php echo $activities['group_activity_id']; ?>"></div>
                    				<div class="join-ride-butn" id="joinactivity_outer_<?php echo $activities['group_activity_id']; ?>">
									<?php if($activities['is_member']){ ; ?>
									<?php }else{ ?>
									 
									<?php } ?>
									</div>
                                </div>
                                <div class="activity-members-outer">
                                	<div class="members-head">Members on board  <a href="javascript:void(0)" class="membersonboard" id="<?php echo $activities['group_activity_id']; ?>"><?php echo $activities['member_count']; ?></a></div>
									
                                    <div class="members-list">
									<?php foreach($activities['members'] as $members){ ?>
                                    	<div class="activity-member profile-image-comn">
											<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>" class="profile-img-link">
											<?php if($members->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $members->user_id ?>/66x66/<?php echo $members->profile_photo; ?>" alt="" />
											<?php }else if($members->user_register_type == 'facebook' && $members->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $members->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
                                            <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>"><?php echo $members->user_given_name; ?></a>
                                        </div>
										<?php } ?>
                                        
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="activity-comments">
								<div id="loadmore_<?php echo $activities['group_activity_id']; ?>"><?php if($activities['comment_count']>2){ ?><a href="javascript:void(0)" id="<?php echo $activities['group_activity_id']; ?>" class="loadmore_comments">View <span id="comment_count_<?php echo $activities['group_activity_id']; ?>"><?php echo $activities['comment_count']-2 ;?></span> more comments</a> <?php } ?></div>
								<div id="comment_area<?php echo $activities['group_activity_id']; ?>">
								<?php  
								$arr_comments = array();
								foreach($activities['comments'] as $comments){
									$arr_comments[] = $comments;
								}
								$newcommnt =  array_reverse($arr_comments);
								foreach($newcommnt as $comments){  
								?>
                            	<div class="comments-outer" id="comments-outer-<?php echo $comments->comment_id ?>">
                                    <div class="comment-profil-img">
										<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>" class="profile-img-link">
											<?php if($comments->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $comments->user_id ?>/66x66/<?php echo $comments->profile_photo; ?>" alt="" />
											<?php }else if($comments->user_register_type == 'facebook' && $comments->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $comments->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
										</div>
                                    <div class="comment-text comment-text2" >
                                        <span><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$comments->user_profile_name)) ?>"><?php echo $comments->user_given_name; ?></a></span>
                                         <div id="comment_text_<?php echo $comments->comment_id; ?>"> <?php echo $comments->comment_content; ?></div>
										
										<div><?php if($comments->user_id == $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="edit_comment_<?php echo $comments->comment_id; ?>" class="edit_comment">Edit</a><?php } ?><?php if($comments->user_id == $this->layout()->identity->user_id || $is_admin ||$activities['group_activity_owner_user_id'] == $this->layout()->identity->user_id ){ ?><a href="javascript:void(0)" id="delete_comment_<?php echo $comments->comment_id; ?>" class="delete_comment">Delete</a><?php } ?></div>
										
                                        <div class="activity-comment-like" id="comments_likes<?php echo $comments->comment_id; ?>">
										<?php if($comments->islike){ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-unlikes"><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />
											<?php } ?>
										<?php }else{ ?>
											<?php if($planetdetails->is_member){ ?>
												<a href="javascript:void(0)" id="<?php echo $comments->comment_id ?>" class="comments-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" /></a>
											<?php }else{ ?>
												<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
											<?php } ?>
										<?php }?>
										<?php echo $comments->likes_count; ?>
										</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
								<?php } ?>
								</div>
                                 <?php if($planetdetails->is_member){ ?>
                                <div class="activity-add-comment">
                                	<textarea name="comment" id="comment_<?php echo $activities['group_activity_id']; ?>" class="activity_comments" placeholder="Comment"></textarea>
                                </div>
								<?php } ?>
                            </div>
							<?php } ?>
						 </div>
							<div id="past_activity_loadmore_container" class="btn-loadmore">
								<a href="javascript:void(0)" id="past_activity_loadmore" >Load more</a>
							</div>
					  
					  </div>
					  <div id="tabs_sub-3" style="display:none">
						<div class="activity-calender">
						<center>
							<div id="jMonthCalendar"></div>
						</center>
					<!--	<div class="date-selected">
							<?php echo date("j"); ?> <?php echo date("F"); ?>  
						</div> -->
						<?php //print_r($today_activities); ?>
						</div>
						<div id="calendar_event">
						<?php foreach($today_activities as $activities){?>
                        	<div class="activity-outer">
                            	<div class="activity-profileimg profile-image-comn">
								<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>" class="profile-img-link">
								<?php  if($activities['profile_photo']!=''){ ?>								 
								<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $activities['user_id']; ?>/66x66/<?php echo $activities['profile_photo']; ?>" alt="" />
								<?php }else if($activities['user_register_type'] == 'facebook' && $activities['user_fbid']!=''){ ?>
									<img src="https://graph.facebook.com/<?php echo $activities['user_fbid']; ?>/picture?width=66&&height=66" />
								<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
								<?php } ?>
								</a>
								</div>
                                <div class="activity-main-outer">
                                	<div class="activity-author"><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$activities['user_profile_name'])) ?>"><?php echo $activities['user_given_name']; ?></a></div>
                                    <div class="activity-text"><a href="<?php echo $this->url('activity/activity-view', array('action' => 'view', 'group_id'=>$planetdetails->galexy_seo_title, 'planet_id'=>$planetdetails->group_seo_title,'id'=>$activities['group_activity_id'])) ?>"><?php echo $activities['group_activity_title']; ?> <span>on <?php echo date("F d,g A",strtotime($activities['group_activity_start_timestamp'])) ?> .</span></a></div>
                                    <div class="activity-details_planet">
                                        <div class="like-comment-outer">
                                            <div class="likes" id="likes_<?php echo $activities['group_activity_id']; ?>">
											<?php if($activities['activity_like']->is_liked){  ?>
												<?php if($planetdetails->is_member){ ?>
													<a href="javascript:void(0)"  class="activity-unlikes" id="<?php echo $activities['group_activity_id']; ?>"  ><img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" />  </a>
												<?php }else{  ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/likes-icon.png" alt="" /> 
												<?php }
											}else{ ?> 
												<?php if($planetdetails->is_member){ ?>	
													<a href="javascript:void(0)" id="<?php echo $activities['group_activity_id']; ?>" class="activity-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />  </a>
												<?php }else{ ?>
													<img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" />
												<?php } ?>
											<?php } ?>
											<?php if($activities['activity_like']->likes_counts){echo $activities['activity_like']->likes_counts;} ?>
											</div>
                                            <div class="likes"><a href="javascript:void(0)"><img src="<?php echo $this->basePath(); ?>/public/images/comments-icon.png" alt="" /></a> <?php if($activities['comment_count']){echo $activities['comment_count'];} ?> <span><a href="javascript:void(0)">Comment</a></span></div>
                                            <div class="clear"></div>
                                        </div>
                                        <div class="activity-location"><?php echo $activities['group_activity_location']; ?></div>
                                         
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                <div class="join-activity-outer">
                                	<div class="activity-rocket<?php if($activities['is_member']){ echo "-member"; } ?>" id="joinactivity_rocket_<?php echo $activities['group_activity_id']; ?>"></div>
                    				<div class="join-ride-butn" id="joinactivity_outer_<?php echo $activities['group_activity_id']; ?>">
									<?php if($activities['is_member']){ ; ?>
									<?php }else{ ?>
									 
									<?php } ?>
									</div>
                                </div>
                                <div class="activity-members-outer">
                                	<div class="members-head">Members on board  <a href="javascript:void(0)" class="membersonboard" id="<?php echo $activities['group_activity_id']; ?>"><?php echo $activities['member_count']; ?></a></div>
									
                                    <div class="members-list">
									<?php foreach($activities['members'] as $members){ ?>
                                    	<div class="activity-member profile-image-comn">
											<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>" class="profile-img-link">
											<?php if($members->profile_photo!=''){ ?>
											<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $members->user_id ?>/66x66/<?php echo $members->profile_photo; ?>" alt="" />
											<?php }else if($members->user_register_type == 'facebook' && $members->user_fbid!=''){ ?>
												<img src="https://graph.facebook.com/<?php echo $members->user_fbid; ?>/picture?width=66&&height=66" />
											<?php }else{ ?>
											<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
											<?php } ?>
											</a>
                                            <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$members->user_profile_name)) ?>"><?php echo $members->user_given_name; ?></a>
                                        </div>
										<?php } ?>
                                        
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                             
							<?php } ?>
						</div>
					  </div>
			</div>
		 </div>
	</div>
 </div>
 <?php }else{ ?>
	<div class="no-member-message">
		You must be a member of this group to see all informations..
		<?php if($group_settings->group_member_join_type=='NoOne'){ ?>
			This group is closed now.. 
		<?php }else if($is_request){ ?>
			You are already requested for membership. Please wait until admin will approve your request
		<?php } ?>
		<div class="join-group-btn">
		<?php if(isset($group_settings)&&!empty($group_settings)&&$group_settings->group_member_join_type!='NoOne'&&!$is_request&&!$planetdetails->is_member){
				?><a href="javascript:void(0);" class="blue-butn" id="join_group">Join this group</a> <?php }  ?> 
		</div>
	</div>
 <?php } ?>
 <div id="all-members-dialog" style="display:none"></div>
   <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 <style>
	#map-canvas, #activity_map{
  height: 400px;

  border: 1px solid #999;
  -moz-box-shadow:    0px 0px 5px #ccc;
  -webkit-box-shadow: 0px 0px 5px #ccc;
  box-shadow:         0px 0px 5px #ccc;
}
 </style>
 <script>
  <?php if($planetdetails->y2m_group_location_lat!=''&&$planetdetails->y2m_group_location_lng!=''){ ?>
		var current_lat = <?php echo $planetdetails->y2m_group_location_lat; ?>;
		var current_lng = <?php echo $planetdetails->y2m_group_location_lng; ?>;
	 <?php }else{  ?>
		var current_lat = 25.271139000000000000;
		var current_lng =55.307485000000040000;
	 <?php } ?>
var geocoder;
var map;
var marker;
var mapselected = 'map1';
// initialise the google maps objects, and add listeners
function gmaps_init(){

  // center of the universe
  var latlng = new google.maps.LatLng(current_lat,current_lng);

  var options = {
    zoom: 7,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP,

  };

  // create our map object
  if(mapselected=='map1')
  map = new google.maps.Map(document.getElementById("map-canvas"), options);
  else
   map = new google.maps.Map(document.getElementById("activity_map"), options);

  // the geocoder object allows us to do latlng lookup based on address
  geocoder = new google.maps.Geocoder();
	 

  // the marker shows us the position of the latest address
  marker = new google.maps.Marker({
    map: map,
	icon: "<?php echo $this->basepath(); ?>/public/images/rocket2-icon.png",
    draggable: true
  });
marker.setPosition(latlng);
  // event triggered when marker is dragged and dropped
  google.maps.event.addListener(marker, 'dragend', function() {
    geocode_lookup( 'latLng', marker.getPosition() );
  });

  // event triggered when map is clicked
  google.maps.event.addListener(map, 'click', function(event) {
    marker.setPosition(event.latLng)
    geocode_lookup( 'latLng', event.latLng  );
  });

  $('#gmaps-error').hide();
}

// move the marker to a new position, and center the map on it
function update_map( geometry ) {
  map.fitBounds( geometry.viewport )
  marker.setPosition( geometry.location )
}

// fill in the UI elements with new position data
function update_ui( address, latLng ) {
if(mapselected=='map1'){
  $('#location').autocomplete("close");
  $('#location').val(address);
  }else{
   $('#address').autocomplete("close");
  $('#address').val(address);
  }
  geo_latitude = latLng.lat(); 
  geo_longitude = latLng.lng(); 
  //$('#gmaps-output-latitude').html(latLng.lat());
  //$('#gmaps-output-longitude').html(latLng.lng());
}

// Query the Google geocode object
//
// type: 'address' for search by address
//       'latLng'  for search by latLng (reverse lookup)
//
// value: search query
//
// update: should we update the map (center map and position marker)?
function geocode_lookup( type, value, update ) {
  // default value: update = false
  update = typeof update !== 'undefined' ? update : false;

  request = {};
  request[type] = value;

  geocoder.geocode(request, function(results, status) {
    $('#gmaps-error').html('');
    $('#gmaps-error').hide();
    if (status == google.maps.GeocoderStatus.OK) {
      // Google geocoding has succeeded!
      if (results[0]) {
        // Always update the UI elements with new location data
        update_ui( results[0].formatted_address,
                   results[0].geometry.location )

        // Only update the map (position marker and center map) if requested
        if( update ) { update_map( results[0].geometry ) }
      } else {
        // Geocoder status ok but no results!?
        $('#gmaps-error').html("Sorry, something went wrong. Try again!");
        $('#gmaps-error').show();
      }
    } else {
      // Google Geocoding has failed. Two common reasons:
      //   * Address not recognised (e.g. search for 'zxxzcxczxcx')
      //   * Location doesn't map to address (e.g. click in middle of Atlantic)

      if( type == 'address' ) {
        // User has typed in an address which we can't geocode to a location
        $('#gmaps-error').html("Sorry! We couldn't find " + value + ". Try a different search term, or click the map." );
        $('#gmaps-error').show();
      } else {
        // User has clicked or dragged marker to somewhere that Google can't do a reverse lookup for
        // In this case we display a warning, clear the address box, but fill in LatLng
        $('#gmaps-error').html("Woah... that's pretty remote! You're going to have to manually enter a place name." );
        $('#gmaps-error').show();
        update_ui('', value)
      }
    };
  });
};

// initialise the jqueryUI autocomplete element
function autocomplete_init() {
	if(mapselected=='map1'){
  $("#location").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }else{
	  $("#address").autocomplete({

    // source is the list of input options shown in the autocomplete dropdown.
    // see documentation: http://jqueryui.com/demos/autocomplete/
    source: function(request,response) {

      // the geocode method takes an address or LatLng to search for
      // and a callback function which should process the results into
      // a format accepted by jqueryUI autocomplete
      geocoder.geocode( {'address': request.term }, function(results, status) {
        response($.map(results, function(item) {
          return {
            label: item.formatted_address, // appears in dropdown box
            value: item.formatted_address, // inserted into input element when selected
            geocode: item                  // all geocode data: used in select callback event
          }
        }));
      })
    },

    // event triggered when drop-down option selected
    select: function(event,ui){
      update_ui(  ui.item.value, ui.item.geocode.geometry.location )
      update_map( ui.item.geocode.geometry )
    }
  });
  }
if(mapselected=='map1'){
  // triggered when user presses a key in the address box
  $("#location").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#location').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#location').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#location').autocomplete("enable")
    }
  });
  }
  else{
	$("#address").bind('keydown', function(event) {
    if(event.keyCode == 13) {
      geocode_lookup( 'address', $('#address').val(), true );

      // ensures dropdown disappears when enter is pressed
      $('#address').autocomplete("disable")
    } else {
      // re-enable if previously disabled above
      $('#address').autocomplete("enable")
    }
  });
  }
}; // autocomplete_init


$(document).ready(function() {
			var options = {
				height: 150,
				width: 980,
				navHeight: 25,
				labelHeight: 25,
				onMonthChanging: function(dateIn) {
					//this could be an Ajax call to the backend to get this months events
					//var events = [ 	{ "EventID": 7, "StartDate": new Date(2009, 1, 1), "Title": "10:00 pm - EventTitle1", "URL": "#", "Description": "This is a sample event description", "CssClass": "Birthday" },
					//				{ "EventID": 8, "StartDate": new Date(2009, 1, 2), "Title": "9:30 pm - this is a much longer title", "URL": "#", "Description": "This is a sample event description", "CssClass": "Meeting" }
					//];
					//$.jMonthCalendar.ReplaceEventCollection(events);
					return true;
				},
				onEventLinkClick: function(event) { 
					alert("event link click");
					return true; 
				},
				onEventBlockClick: function(event) { 
					alert("block clicked");
					return true; 
				},
				onEventBlockOver: function(event) {
					//alert(event.Title + " - " + event.Description);
					return true;
				},
				onEventBlockOut: function(event) {
					return true;
				},
				onDayLinkClick: function(date) { 
					//var selected_date = date.toLocaleDateString();
					//var arr_selected_date = selected_date.split(" ");
					//$(".date-selected").html(arr_selected_date[0]+" "+arr_selected_date[1]);
					 
					options = { year: "numeric", month: "numeric",
					day: "numeric" };
					//alert(date.toLocaleDateString());
					var url = baseurl + "/activity/OneDayOnly";
					var callback = $.ajax({
						type: "post",
						url: url,
						data:{
							'group': galexy,
							'planet': planet,
							'selected_date':date.toLocaleDateString(),							 
						}, // serializes the form's elements.
						success: function(data)
						{
						$("#calendar_event").html(data);
						past_activity_page++; 
							
						}
					});	
					return false; 
				},
				onDayCellClick: function(date) { 
				 
					//	var selected_date = date.toLocaleDateString();
				///	var arr_selected_date = selected_date.split(" ");
				//	$(".date-selected").html(arr_selected_date[0]+" "+arr_selected_date[1]);
					var url = baseurl + "/activity/OneDayOnly";					 
					var callback = $.ajax({
						type: "post",
						url: url,
						data:{
							'group': galexy,
							'planet': planet,
							'selected_date':date.toLocaleDateString(),							 
						}, // serializes the form's elements.
						success: function(data)
						{
						$("#calendar_event").html(data);
						past_activity_page++; 	
						}
					});	
					return false;
					return true; 
				}
			};
			
			
			var events = [ 
			];
			
			var newoptions = { };
			var newevents = [ ];
			//$.jMonthCalendar.Initialize(newoptions, newevents);

			
			$.jMonthCalendar.Initialize(options, events);
			
			
			
			
			var extraEvents = [
			];
			 		
			 
        });
		
</script>