<?php echo $this->doctype(); ?> 
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('1625 '. $this->translate('Explore Yourself'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
						->prependStylesheet($this->basePath() . '/css/jquery.bxslider.css');
						?>

        <!-- Scripts -->
		<?php echo $this->headScript(); ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                       ->prependFile($this->basePath() . '/js/1625.js')
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ;								  
									  ?>

    	 
	
	</head>
    <body>
        <div class="header-container">
		<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('1625') ?></a>
					<br class="clear:both"/>
					<br class="clear:both"/>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            
							 
							 <?php 
							 	if(isset($this->layout()->identity) && $this->layout()->identity!=NULL){
							 ?>
								
								<li class="active"><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Home') ?></a></li>
								 
								<li class="active"><a href="<?php echo $this->url('user/logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
								<?php }else{ ?>
								<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
								<li class="active"><a href="<?php echo $this->url('user/register') ?>"><?php echo $this->translate('Register') ?></a></li>
								<li class="active"><a href="<?php echo $this->url('user/login') ?>"><?php echo $this->translate('Login') ?></a></li>
							
								<?php } ?>
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
		</div>
		<div class="content-container">
		<div class="content-inner">
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Y2M. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
		</div>
		</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
