<?php 
if(!empty($error)){
	foreach($error as $msg){
		echo $msg."<br />";
	}
}
 ?>
<div class="comments-outer comments-outer-<?php echo $module_comments->comment_id; ?>" id="comments-outer-<?php echo $module_comments->comment_id; ?>">
	<div class="comment-profil-img">
		<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$module_comments->user_profile_name)) ?>" class="profile-img-link">
		<?php if($module_comments->profile_photo!=''){ ?>
		<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $module_comments->user_id ?>/66x66/<?php echo $module_comments->profile_photo; ?>" alt="" />
		<?php }else if($module_comments->user_register_type == 'facebook' && $module_comments->user_fbid!=''){ ?>
			<img src="https://graph.facebook.com/<?php echo $module_comments->user_fbid; ?>/picture?width=66&&height=66" />
		<?php }else{ ?>
		<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
		<?php } ?>
		</a>
		</div>
	<div class="comment-text comment-text2">
		<span><a href="<?php echo $this->url('memberprofile',array('member_profile'=>$module_comments->user_profile_name)) ?>"><?php echo $module_comments->user_given_name; ?></a></span>
		<div id="comment_text_<?php echo $module_comments->comment_id; ?>" class="comment_text_<?php echo $module_comments->comment_id; ?>"> <?php echo $module_comments->comment_content; ?></div>
		 
		<div><a href="javascript:void(0)" id="edit_comment_<?php echo $module_comments->comment_id; ?>" class="edit_comment">Edit</a>&nbsp;<a href="javascript:void(0)" id="delete_comment_<?php echo $module_comments->comment_id; ?>" class="delete_comment">Delete</a></div>
		 
		<div class="activity-comment-like comments_likes<?php echo $module_comments->comment_id; ?>" id="comments_likes<?php echo $module_comments->comment_id; ?>"><a href="javascript:void(0)"id="<?php echo $module_comments->comment_id ?>" class="comments-likes"><img src="<?php echo $this->basePath(); ?>/public/images/nolike-icon.png" alt="" /></a><?php //echo $comments->likes_count; ?></div>
	</div>
	<div class="clear"></div>
</div>
 